table _Miary
	lineageTag: fce809bd-c1a1-4265-b842-278345ddfbe1

	measure Wydatki =
			
			COALESCE(
			    SUM(f_capex_imp_cost_data[amount_pln]),
			    0
			)
		formatString: #,0
		lineageTag: 295b12e5-d9a0-457b-a5b2-7fcb9103c641

	measure 'Nazwa projektu - tytul' =
			
			IF( NOT ISFILTERED(vm_pbi_d_gl_project[prj_desc]),
			    "Wybierz projekt",
			    IF( HASONEVALUE(vm_pbi_d_gl_project[prj_desc]),
			        VALUES(vm_pbi_d_gl_project[prj_desc]),
			        "Kilka projektów" )
			)
		lineageTag: b6e08fcd-fedb-45b4-bb85-c74858294be6

	measure 'Ilość otwartych projektów' =
			
			COUNTROWS (
			    DISTINCT(
			        FILTER(
			            VALUES('vm_pbi_d_gl_project'[prj_desc]),
			            LEFT ('vm_pbi_d_gl_project'[prj_desc], 3) <> "(X)"
			        )
			    )
			)
		formatString: 0
		lineageTag: d8358878-8d59-40fd-a985-73ad8eae745c

	measure 'Ilosc otwartych projektow wg statusow' =
			
			
			COUNTROWS(
			    DISTINCT(
			    FILTER(
			        vm_pbi_d_gl_project,
			        vm_pbi_d_gl_project[status] = "Aktywny"
			    )
			)
			)
		formatString: 0
		lineageTag: ff3f4611-a439-44b2-a121-51817b979cd1

	measure 'Numer projektu - tytul' =
			
			IF( NOT ISFILTERED(vm_pbi_d_gl_project[prj_desc]),
			    "Wybierz projekt",
			    IF( HASONEVALUE(vm_pbi_d_gl_project[hprj_code]),
			        VALUES(vm_pbi_d_gl_project[hprj_code]),
			        "Kilka projektów")
			)
		lineageTag: 0490d09a-711e-4302-9875-25436384c6c6

	measure 'Budzet projektu' =
			
			COALESCE(
			    SUM(vm_pbi_d_projects_budget[debet_amount]),
			    0
			)
		formatString: #,0
		lineageTag: 467e429d-ecbc-48a8-8151-48417635da7e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Realizacja budzetu %' = ```
			
			VAR Budzet_projektu = 
			    SUM(vm_pbi_d_projects_budget[debet_amount])
			
			VAR Wydatki = 
			    SUM(f_capex_imp_cost_data[amount_pln])
			
			RETURN
			
			DIVIDE(
			    [Wydatki],
			    [Budzet projektu],
			    ""
			 )
			
			```
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 0a1ed71e-7a2c-4f4e-928f-e3600efa60d1

	measure Przyszly_rok =
			
			YEAR(
			    NOW()
			) + 1
		formatString: 0
		lineageTag: 5ca79c38-862a-40c6-826e-1f390723fb89

	measure 'Widocznosc grafiki' = ```
			
			IF(
			    HASONEVALUE(vm_pbi_d_gl_project[prj_desc]),
			    "RGBA(255,0,0,0)",         
			    "RGBA(255,255,255,1)"
			)
			
			```
		lineageTag: a6dacdac-9fa3-4da3-b234-913ccc9fdc1b

	measure 'Budzet projektu (blank)' = ```
			
			    SUM(vm_pbi_d_projects_budget[debet_amount])
			
			```
		formatString: #,0
		lineageTag: 9d24a183-b6ed-4b1c-a704-6e5608b789a9

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Wydatki (blank)' = ```
			
			    SUM(f_capex_imp_cost_data[amount_pln])
			
			```
		formatString: #,0
		lineageTag: 29184878-cc4b-46f5-8e71-e83cbc1758d4

		annotation PBI_FormatHint = {"isDecimal":true}

	column Value
		formatString: 0
		lineageTag: 7128fcce-d1b2-4ff6-9247-20bcb975a017
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Miary = calculated
		mode: import
		source = {0}

	annotation PBI_Id = 8ff54b4d66f14635a814d7d3fdcc4732

