table vm_pbi_f_lines_sales
	lineageTag: 031e982a-88c4-4807-9706-366d4eb500ea

	measure SPRZEDAZ_linii =
			
			SUM(vm_pbi_f_lines_sales[s_pln_net])
		formatString: #,0
		lineageTag: 5a3aef2e-a9b8-404b-aecf-e44f085ee83f

	measure sprzedaz_koszt =
			
			DIVIDE([SPRZEDAZ_linii],[Wydatki])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: da84a9dc-5a02-4fb8-ba14-3d608eb551f0

	column line_name
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 26dc791c-0c62-465b-9846-3729d8a8f15f
		summarizeBy: none
		sourceColumn: line_name

		annotation SummarizationSetBy = Automatic

	column s_pln_net
		dataType: int64
		formatString: #,0
		sourceProviderType: int
		lineageTag: 7361c70e-4ee0-43b5-adb7-633ece765f3c
		summarizeBy: sum
		sourceColumn: s_pln_net

		annotation SummarizationSetBy = Automatic

	partition vm_pbi_f_lines_sales = m
		mode: directQuery
		source =
				let
				    Źródło = Databricks.Catalogs("adb-16306551450739.19.azuredatabricks.net", "/sql/1.0/warehouses/d77ff9935cb3e9fe", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation="2.0"]),
				    controlling_Database = Źródło{[Name="controlling",Kind="Database"]}[Data],
				    capex_implement_Schema = controlling_Database{[Name="capex_implement",Kind="Schema"]}[Data],
				    vm_pbi_f_lines_sales_View = capex_implement_Schema{[Name="vm_pbi_f_lines_sales",Kind="View"]}[Data],
				    #"Zmieniono typ" = Table.TransformColumnTypes(vm_pbi_f_lines_sales_View,{{"s_pln_net", Int64.Type}}),
				    #"Usunięto kolumny" = Table.RemoveColumns(#"Zmieniono typ",{"year_name"})
				in
				    #"Usunięto kolumny"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

