table CBR_data
	lineageTag: 7b040ac1-69cb-406a-89cc-0eeb2713c4c0

	column Name
		dataType: string
		lineageTag: 370a985a-c40f-434e-a791-0440a235134f
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: e7fd826d-a70f-42c8-a33d-71120d9999bb
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Originated
		dataType: dateTime
		formatString: Long Date
		lineageTag: bc303f9c-8738-46d9-8ed0-ee3ce70ea958
		summarizeBy: none
		sourceColumn: Originated

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Contractor / Kontrahent'
		dataType: string
		lineageTag: 67c617c2-ac1a-4fe2-b0f1-2a9de06e9ae1
		summarizeBy: none
		sourceColumn: Contractor / Kontrahent

		annotation SummarizationSetBy = Automatic

	column 'Commercial project / Projekt handlowy'
		dataType: string
		lineageTag: 069b4fbe-843e-4485-8674-2979710af115
		summarizeBy: none
		sourceColumn: Commercial project / Projekt handlowy

		annotation SummarizationSetBy = Automatic

	column 'Implementation project / Projekt wdrozeniowy'
		dataType: string
		lineageTag: 832d27c3-ac91-4399-b1cb-e082797d520a
		summarizeBy: none
		sourceColumn: Implementation project / Projekt wdrozeniowy

		annotation SummarizationSetBy = Automatic

	column 'Wniosek do'
		dataType: string
		lineageTag: b91b37c0-3810-44f7-8661-4a440747b049
		summarizeBy: none
		sourceColumn: Wniosek do

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: string
		lineageTag: faa37eb5-03fe-431f-922a-91883565ae15
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Quantity on customer order / Ilość na zamówieniu klienta'
		dataType: string
		lineageTag: b3f2f700-a698-4af3-8ec2-72c3880e04ce
		summarizeBy: none
		sourceColumn: Quantity on customer order / Ilość na zamówieniu klienta

		annotation SummarizationSetBy = Automatic

	column 'Request type / Typ wniosku'
		dataType: string
		lineageTag: 68a52bcc-51d4-4997-874a-f840170cac47
		summarizeBy: none
		sourceColumn: Request type / Typ wniosku

		annotation SummarizationSetBy = Automatic

	column 'Project manager / Kierownik projektu'
		dataType: string
		lineageTag: 7cc27201-28d9-44dd-b1b8-07cf77c2a597
		summarizeBy: none
		sourceColumn: Project manager / Kierownik projektu

		annotation SummarizationSetBy = Automatic

	column 'Construction leader / Kierownik komorki konstrukcyjnej'
		dataType: string
		lineageTag: 2624a3a6-ad74-4dfa-9f64-ba88b4701809
		summarizeBy: none
		sourceColumn: Construction leader / Kierownik komorki konstrukcyjnej

		annotation SummarizationSetBy = Automatic

	column 'Responsible engineer / Konstruktor prowadzacy'
		dataType: string
		lineageTag: 61086fd1-060a-470b-a2d9-0d44bed1d555
		summarizeBy: none
		sourceColumn: Responsible engineer / Konstruktor prowadzacy

		annotation SummarizationSetBy = Automatic

	column 'Sygnatura SP / SP Signature'
		dataType: string
		lineageTag: 80ff08ca-98a8-41cf-879c-f854190b04ff
		summarizeBy: none
		sourceColumn: Sygnatura SP / SP Signature

		annotation SummarizationSetBy = Automatic

	column 'Customer order number / Numer zamówienia klienta'
		dataType: string
		lineageTag: 26175a56-abb3-4570-a261-8a9e654a846d
		summarizeBy: none
		sourceColumn: Customer order number / Numer zamówienia klienta

		annotation SummarizationSetBy = Automatic

	column 'Customer order activation date / Data aktywacji zamówienia klienta'
		dataType: string
		lineageTag: 33fed5a1-a4c4-4b9d-bad1-a4a4e8b16d46
		summarizeBy: none
		sourceColumn: Customer order activation date / Data aktywacji zamówienia klienta

		annotation SummarizationSetBy = Automatic

	column 'Planned shipping date / Planowana data wysyłki'
		dataType: string
		lineageTag: d51206b2-518c-456f-b69b-0e7357646052
		summarizeBy: none
		sourceColumn: Planned shipping date / Planowana data wysyłki

		annotation SummarizationSetBy = Automatic

	column 'Requested implementation date / Zadany termin zakonczenia wdrozenia'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e46f7bf3-0267-4895-8eb9-72669c9de3da
		summarizeBy: none
		sourceColumn: Requested implementation date / Zadany termin zakonczenia wdrozenia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Requested order completion date / Wymagany termin realizacji zamowienia'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 47f60074-2b6e-4d4f-b782-ebe418677f85
		summarizeBy: none
		sourceColumn: Requested order completion date / Wymagany termin realizacji zamowienia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Description / Opis'
		dataType: string
		lineageTag: c32e2eb0-88f9-48e5-aa2d-bb35e441223e
		summarizeBy: none
		sourceColumn: Description / Opis

		annotation SummarizationSetBy = Automatic

	column Column21
		dataType: string
		lineageTag: 4268f22d-0342-4af9-9872-7012c31d3a55
		summarizeBy: none
		sourceColumn: Column21

		annotation SummarizationSetBy = Automatic

	column 'NPI Link'
		dataType: string
		lineageTag: 692364b5-835c-414a-bebb-57e2b11f64ee
		summarizeBy: none
		sourceColumn: NPI Link

		annotation SummarizationSetBy = Automatic

	column 'Task name'
		dataType: string
		lineageTag: b6c4ed19-9d02-4c4d-8683-a7938376f9c3
		summarizeBy: none
		sourceColumn: Task name

		annotation SummarizationSetBy = Automatic

	column 'Task duration [h]'
		dataType: double
		lineageTag: 83153826-9fe2-4f12-8988-90e7ad01902f
		summarizeBy: sum
		sourceColumn: Task duration [h]

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Task Description'
		dataType: string
		lineageTag: 0010a5d2-37bc-49a7-be9c-b7fbe35e5b33
		summarizeBy: none
		sourceColumn: Task Description

		annotation SummarizationSetBy = Automatic

	column 'Task Comment'
		dataType: string
		lineageTag: 2d016dd9-18b6-4435-a0e8-9b2a8dfcf387
		summarizeBy: none
		sourceColumn: Task Comment

		annotation SummarizationSetBy = Automatic

	column 'Task Assigned person'
		dataType: string
		lineageTag: 485ca184-582e-4ed5-9167-8bc13eb30644
		summarizeBy: none
		sourceColumn: Task Assigned person

		annotation SummarizationSetBy = Automatic

	column 'Task Sekcja'
		dataType: string
		lineageTag: 76ab888e-2750-425d-b871-e00994286414
		summarizeBy: none
		sourceColumn: Task Sekcja

		annotation SummarizationSetBy = Automatic

	column Column29
		dataType: string
		lineageTag: 83f762c8-c77b-4fb0-b790-d84a8b6baa97
		summarizeBy: none
		sourceColumn: Column29

		annotation SummarizationSetBy = Automatic

	column 'Task Link'
		dataType: string
		lineageTag: 6869b82e-5b4f-467d-b3ab-da0f7629b447
		summarizeBy: none
		sourceColumn: Task Link

		annotation SummarizationSetBy = Automatic

	partition CBR_data = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\lukasz.wojcik\OneDrive - Nowy Styl Sp. z o.o\Dokumenty\GitHub\NS-PBI\NPI request\NPI_Zadania_2024-2026.xlsx"), null, true),
				    DANE1_Sheet = Source{[Item="DANE1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(DANE1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Name", type text}, {"State", type text}, {"Originated", type date}, {"Contractor / Kontrahent", type text}, {"Commercial project / Projekt handlowy", type text}, {"Implementation project / Projekt wdrozeniowy", type text}, {"Wniosek do", type text}, {"Index", type text}, {"Quantity on customer order / Ilość na zamówieniu klienta", type any}, {"Request type / Typ wniosku", type text}, {"Project manager / Kierownik projektu", type text}, {"Construction leader / Kierownik komorki konstrukcyjnej", type text}, {"Responsible engineer / Konstruktor prowadzacy", type text}, {"Sygnatura SP / SP Signature", type text}, {"Customer order number / Numer zamówienia klienta", type text}, {"Customer order activation date / Data aktywacji zamówienia klienta", type text}, {"Planned shipping date / Planowana data wysyłki", type text}, {"Requested implementation date / Zadany termin zakonczenia wdrozenia", type date}, {"Requested order completion date / Wymagany termin realizacji zamowienia", type date}, {"Description / Opis", type text}, {"Column21", type text}, {"NPI Link", type text}, {"Task name", type text}, {"Task duration [h]", type number}, {"Task Description", type text}, {"Task Comment", type text}, {"Task Assigned person", type text}, {"Task Sekcja", type text}, {"Column29", type text}, {"Task Link", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

