table f_margin75_facts
	lineageTag: 6afe1b3b-8ba2-4b94-8585-14545a4fc805

	measure 'Assembly EUR' = SUM(f_margin75_facts[c_eur_assembly])
		formatString: #,0
		lineageTag: 05230736-9b76-4963-a1b2-03a2d5469718

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Assembly PLN' = SUM(f_margin75_facts[c_pln_assembly])
		formatString: #,0
		lineageTag: 670c7ffd-eb2f-4571-9e85-c0964f17667d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Base Sales EUR' = SUM(f_margin75_facts[s_eur_base])
		formatString: #,0
		lineageTag: 77913062-840f-47cd-8df7-bcf99a97fbf8

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Base Sales PLN' = SUM(f_margin75_facts[s_pln_base])
		formatString: #,0
		lineageTag: 911e2658-38cb-424d-ae90-43231a11e30f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Commission EUR' = SUM(f_margin75_facts[c_eur_comm])
		formatString: #,0
		lineageTag: 8ced0897-ba0e-4c84-9d03-9a6748c660fd

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Commission PLN' = SUM(f_margin75_facts[c_pln_comm])
		formatString: #,0
		lineageTag: bb7e116e-f4e0-489a-9039-47be09d4bc9f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Complaint Activity EUR' = SUM(f_margin75_facts[c_eur_compl_act])
		formatString: #,0
		lineageTag: 0b1206e8-9453-4ec3-8e56-73cf38e1f70d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Complaint Activity PLN' = SUM(f_margin75_facts[c_pln_compl_act])
		formatString: #,0
		lineageTag: f323d3ab-fb09-47ad-a793-2792c3c90328

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Complaint Product EUR' = SUM(f_margin75_facts[c_eur_compl_prod])
		formatString: #,0
		lineageTag: c833b979-552a-4a9f-8eeb-976437330c83

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Complaint Product PLN' = SUM(f_margin75_facts[c_pln_compl_prod])
		formatString: #,0
		lineageTag: 50f1bdcf-f91f-40f1-b577-470250ff5258

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'License EUR' = SUM(f_margin75_facts[c_eur_lic])
		formatString: #,0
		lineageTag: ba241dff-404b-44d8-a9e1-6708d49af582

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'License PLN' = SUM(f_margin75_facts[c_pln_lic])
		formatString: #,0
		lineageTag: e7daf5ed-8873-427c-90cf-3651610ec0d3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Manufacturing Cost EUR' = SUM(f_margin75_facts[s_eur_corp_cost])
		formatString: #,0
		lineageTag: fa4d7169-0fbf-45a2-9c4f-429666580c72

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Manufacturing Cost PLN' = SUM(f_margin75_facts[s_pln_corp_cost])
		formatString: #,0
		lineageTag: 34c2f3d3-bed1-42ad-b8f8-2afa039977c9

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Net Sales EUR' = SUM(f_margin75_facts[s_eur_net])
		formatString: #,0
		lineageTag: 6d6e2740-f032-44fc-860b-15193b1cce8e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Net Sales PLN' = SUM(f_margin75_facts[s_pln_net])
		formatString: #,0
		lineageTag: 55f0803b-4a71-4ef8-8aa1-295fb81d1fd6

	measure 'Sale Quantity' = SUM(f_margin75_facts[sale_qty])
		formatString: #,0
		lineageTag: 323517ab-2a0f-4cb0-8d1b-d17550be7a38

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Sold Insurance EUR' = SUM(f_margin75_facts[c_eur_sinsuran])
		formatString: #,0
		lineageTag: fb34d2ba-6118-4fb6-9896-2ecccb879b02

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Sold Insurance PLN' = SUM(f_margin75_facts[c_pln_sinsuran])
		formatString: #,0
		lineageTag: 75d1f012-587f-4290-9cfd-10743968399c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Stock Depreciation EUR' = SUM(f_margin75_facts[c_eur_stock_deprec])
		formatString: #,0
		lineageTag: 22fdfdc8-c569-4854-908d-0be84f8c463c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Stock Depreciation PLN' = SUM(f_margin75_facts[c_pln_stock_deprec])
		formatString: #,0
		lineageTag: e767ce40-aba9-44ec-b3cc-513129f37c5c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Transport EUR' = SUM(f_margin75_facts[c_eur_transport])
		formatString: #,0
		lineageTag: 60e073da-c7cd-44fc-8e77-f3a80c0b1e71

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Transport PLN' = SUM(f_margin75_facts[c_pln_transport])
		formatString: #,0
		lineageTag: 04c89d33-f838-4055-84a4-726816104973

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Variance Fixed Cost EUR' = SUM(f_margin75_facts[c_eur_varfixed])
		formatString: #,0
		lineageTag: f5bc0283-969b-494a-bd03-ba0a92660266

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Variance Fixed Cost PLN' = SUM(f_margin75_facts[c_pln_varfixed])
		formatString: #,0
		lineageTag: cda8f03a-3b6c-4338-98b3-97ed4d85593f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Margin I (prim) % (EUR)' = IF([Net Sales EUR] = BLANK(), BLANK(), [Margin I (prim) EUR] / [Net Sales EUR])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e5b08602-50de-438b-8992-5982ff835025

	measure 'Margin I (prim) % (PLN)' = IF([Net Sales PLN] = BLANK(), BLANK(), [Margin I (prim) PLN] / [Net Sales PLN])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 68ffe78a-ba9b-4353-9fad-85e52cf1347a

	measure 'Margin I (prim) EUR' = [Margin I EUR] - [Complaint Product EUR] - [Variance Fixed Cost EUR]
		formatString: #,0
		lineageTag: bbb5b81e-5a2a-4c41-9b15-4a7b884f349c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Margin I (prim) PLN' = [Margin I PLN] - [Complaint Product PLN] - [Variance Fixed Cost PLN]
		formatString: #,0
		lineageTag: baf7fcdd-5e8e-4094-bbab-6b8f96571984

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Margin I % (EUR)' = [Margin I EUR] / [Net Sales EUR]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a6273b70-b8a9-4415-833b-34cfd87d88a0

	measure 'Margin I % (PLN)' = IF([Net Sales PLN] = BLANK(), BLANK(), [Margin I PLN] / [Net Sales PLN])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ed7cdf32-9d4f-4c93-9d16-8fbd8439be85

	measure 'Margin I EUR' = [Net Sales EUR] - [Manufacturing Cost EUR]
		formatString: #,0
		lineageTag: ef8903e8-16a2-499c-8631-effe5428a61b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Margin I PLN' = [Net Sales PLN] - [Manufacturing Cost PLN]
		formatString: #,0
		lineageTag: 233d4736-dbcd-475b-916d-b5fd1e9978f5

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Margin II % (EUR)' = IF([Net Sales EUR] = BLANK(), BLANK(), [Margin II EUR] / [Net Sales EUR])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0b358023-d2ab-46de-a1e0-702b1c9842d5

	measure 'Margin II % (PLN)' = IF([Net Sales PLN] = BLANK(), BLANK(), [Margin II PLN] / [Net Sales PLN])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 66ebfd4b-ef74-4b5b-a54b-ef349cd7efa5

	measure 'Margin II EUR' = [Margin I EUR] - [Assembly EUR] - [Commission EUR] - [Complaint Activity EUR] - [Complaint Product EUR] - [License EUR] - [Sold Insurance EUR] - [Stock Depreciation EUR] - [Transport EUR] - [Variance Fixed Cost EUR]
		formatString: #,0
		lineageTag: 60fc5202-3852-45ea-94d9-65f43a490c17

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Margin II PLN' = [Margin I PLN] - [Assembly PLN] - [Commission PLN] - [Complaint Activity PLN] - [Complaint Product PLN] - [License PLN] - [Sold Insurance PLN] - [Stock Depreciation PLN] - [Transport PLN] - [Variance Fixed Cost PLN]
		formatString: #,0
		lineageTag: fc91ba36-5566-4a1c-af55-79db42c29d96

		annotation PBI_FormatHint = {"isDecimal":true}

	column time_id
		dataType: int64
		formatString: 0
		lineageTag: 0faca851-d696-4f3d-8f8d-843ea9da6150
		summarizeBy: sum
		sourceColumn: time_id

		annotation SummarizationSetBy = Automatic

	column comp_id
		dataType: int64
		formatString: 0
		lineageTag: a1d79b81-ad03-4b7f-87ac-162fbd18664e
		summarizeBy: sum
		sourceColumn: comp_id

		annotation SummarizationSetBy = Automatic

	column cust_id
		dataType: int64
		formatString: 0
		lineageTag: fa613652-e5b6-4769-bf44-ff3ac647b87e
		summarizeBy: none
		sourceColumn: cust_id

		annotation SummarizationSetBy = Automatic

	column prod_inv_id
		dataType: int64
		formatString: 0
		lineageTag: 46e57a2b-980b-4755-813a-06465db5f27a
		summarizeBy: none
		sourceColumn: prod_inv_id

		annotation SummarizationSetBy = Automatic

	column mnf_id
		dataType: int64
		formatString: 0
		lineageTag: e55ddbd9-1406-444f-bf6e-4adb836c1320
		summarizeBy: sum
		sourceColumn: mnf_id

		annotation SummarizationSetBy = Automatic

	column org_id
		dataType: int64
		formatString: 0
		lineageTag: 105874f7-95b4-4e73-8f17-0baf83cfa977
		summarizeBy: sum
		sourceColumn: org_id

		annotation SummarizationSetBy = Automatic

	column team_id
		dataType: int64
		formatString: 0
		lineageTag: 4578bb7f-3464-4a4f-93f0-b6c396d9f37d
		summarizeBy: sum
		sourceColumn: team_id

		annotation SummarizationSetBy = Automatic

	column d_term_id
		dataType: int64
		formatString: 0
		lineageTag: 111de334-33d3-44da-af72-0df0d386deb8
		summarizeBy: sum
		sourceColumn: d_term_id

		annotation SummarizationSetBy = Automatic

	column comp_cost_id
		dataType: int64
		formatString: 0
		lineageTag: 3b077c61-4eba-483e-a8f1-5ef54071b4e0
		summarizeBy: sum
		sourceColumn: comp_cost_id

		annotation SummarizationSetBy = Automatic

	column pricelist_id
		dataType: int64
		formatString: 0
		lineageTag: dbf7d463-2435-4351-9138-7a9aa90921bd
		summarizeBy: sum
		sourceColumn: pricelist_id

		annotation SummarizationSetBy = Automatic

	column mon_name
		dataType: string
		lineageTag: 206eae14-4fb1-4682-b9c3-4af720d92dd6
		summarizeBy: none
		sourceColumn: mon_name

		annotation SummarizationSetBy = Automatic

	column comp_code
		dataType: string
		lineageTag: e79aa16e-37a2-4480-8898-44430c829498
		summarizeBy: none
		sourceColumn: comp_code

		annotation SummarizationSetBy = Automatic

	column cust_code
		dataType: string
		lineageTag: c8a1f939-db99-4f64-b3f6-27ea0ba37717
		summarizeBy: none
		sourceColumn: cust_code

		annotation SummarizationSetBy = Automatic

	column prod_si_code
		dataType: string
		lineageTag: 71c1908f-e281-4045-a5a7-9600a138c4e3
		summarizeBy: none
		sourceColumn: prod_si_code

		annotation SummarizationSetBy = Automatic

	column sman_code
		dataType: string
		lineageTag: fe4ea506-2c76-4afb-b5c8-b10234184cf7
		summarizeBy: none
		sourceColumn: sman_code

		annotation SummarizationSetBy = Automatic

	column team_code
		dataType: string
		lineageTag: 075fcaee-c36e-4ec1-985c-43500cb0a8d8
		summarizeBy: none
		sourceColumn: team_code

		annotation SummarizationSetBy = Automatic

	column dept_code
		dataType: string
		lineageTag: b939d350-e425-42a3-908e-3d1572f8fae0
		summarizeBy: none
		sourceColumn: dept_code

		annotation SummarizationSetBy = Automatic

	column d_term_code
		dataType: string
		lineageTag: ae8c9142-a707-4108-9991-cf895ec8ea7d
		summarizeBy: none
		sourceColumn: d_term_code

		annotation SummarizationSetBy = Automatic

	column sale_qty
		dataType: double
		lineageTag: db6ea762-9e3e-4e2a-baf4-5092a903bd8f
		summarizeBy: sum
		sourceColumn: sale_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_pln_net
		dataType: double
		lineageTag: 91be85b9-17bf-4a26-9080-f118b7aa452a
		summarizeBy: sum
		sourceColumn: s_pln_net

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_eur_net
		dataType: double
		lineageTag: 24192d6e-92d2-4d24-a94b-1ebfd8ad9d06
		summarizeBy: sum
		sourceColumn: s_eur_net

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_pln_corp_cost
		dataType: double
		lineageTag: 24220bd1-54a3-4588-840e-4e2b2c616f35
		summarizeBy: sum
		sourceColumn: s_pln_corp_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_eur_corp_cost
		dataType: double
		lineageTag: 4d159823-1f5f-4cef-94da-951e5be71db9
		summarizeBy: sum
		sourceColumn: s_eur_corp_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_lic
		dataType: double
		lineageTag: ac39b0f9-ecda-488d-8bf5-49349ec5eaf8
		summarizeBy: sum
		sourceColumn: c_pln_lic

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_lic
		dataType: double
		lineageTag: f5e78254-7530-41aa-aaa5-1e9784d13f97
		summarizeBy: sum
		sourceColumn: c_eur_lic

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_pln_base
		dataType: double
		lineageTag: 1487d710-953d-4614-8128-e8f6db52a22e
		summarizeBy: sum
		sourceColumn: s_pln_base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_eur_base
		dataType: double
		lineageTag: 4d73b620-205d-4a1d-bd2a-8d45a9449ba3
		summarizeBy: sum
		sourceColumn: s_eur_base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_varfixed
		dataType: double
		lineageTag: 83f5ae7a-f2df-4199-b17b-da2c2a3c5481
		summarizeBy: sum
		sourceColumn: c_pln_varfixed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_varfixed
		dataType: double
		lineageTag: e5fa6f21-20ce-4da1-961a-0ac950bf60fe
		summarizeBy: sum
		sourceColumn: c_eur_varfixed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_transport
		dataType: double
		lineageTag: e2a63c0c-bc0c-4453-bc84-d687f4603745
		summarizeBy: sum
		sourceColumn: c_pln_transport

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_transport
		dataType: double
		lineageTag: b319a343-8871-483e-8dfc-36a4a7f5223c
		summarizeBy: sum
		sourceColumn: c_eur_transport

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_compl_prod
		dataType: double
		lineageTag: d92e415c-a20c-49d5-a03b-d28984d398b8
		summarizeBy: sum
		sourceColumn: c_pln_compl_prod

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_compl_prod
		dataType: double
		lineageTag: 0e61a0d6-7922-444d-8cb4-08812fde4c05
		summarizeBy: sum
		sourceColumn: c_eur_compl_prod

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_comm
		dataType: double
		lineageTag: 468b9464-ccf2-4fd6-8b84-06b5be5b46de
		summarizeBy: sum
		sourceColumn: c_pln_comm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_comm
		dataType: double
		lineageTag: a2143d59-3047-4894-a859-a3fd85aa3153
		summarizeBy: sum
		sourceColumn: c_eur_comm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_sinsuran
		dataType: double
		lineageTag: 3aec663e-7217-4b59-b2fc-75d1a1fe21e1
		summarizeBy: sum
		sourceColumn: c_pln_sinsuran

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_sinsuran
		dataType: double
		lineageTag: e960012e-033f-4c23-86d8-91c25eaf7887
		summarizeBy: sum
		sourceColumn: c_eur_sinsuran

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_assembly
		dataType: double
		lineageTag: d420fcb1-3dc6-491f-81f7-e327147352df
		summarizeBy: sum
		sourceColumn: c_pln_assembly

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_assembly
		dataType: double
		lineageTag: 0db1813f-ff10-44ba-8942-f2c1db8447f0
		summarizeBy: sum
		sourceColumn: c_eur_assembly

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_stock_deprec
		dataType: double
		lineageTag: 6422a13d-a26b-45d3-b05b-d414dcd69ee7
		summarizeBy: sum
		sourceColumn: c_pln_stock_deprec

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_stock_deprec
		dataType: double
		lineageTag: fb968727-e5f9-46f3-a3b5-d150f7445be1
		summarizeBy: sum
		sourceColumn: c_eur_stock_deprec

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_compl_act
		dataType: double
		lineageTag: 9121a759-a2b5-4aca-87bc-f765a149e990
		summarizeBy: sum
		sourceColumn: c_pln_compl_act

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_compl_act
		dataType: double
		lineageTag: 06459019-b41f-47e4-8dc4-8e38e1dab63f
		summarizeBy: sum
		sourceColumn: c_eur_compl_act

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition f_margin75_facts = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-16306551450739.19.azuredatabricks.net", "/sql/1.0/warehouses/d77ff9935cb3e9fe", [Catalog="zenith", Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null, MetricViewBiCompatibilityMode=null]),
				    zenith_Database = Source{[Name="zenith",Kind="Database"]}[Data],
				    mmo75_Schema = zenith_Database{[Name="mmo75",Kind="Schema"]}[Data],
				    f_margin75_facts_Table = mmo75_Schema{[Name="f_margin75_facts",Kind="Table"]}[Data]
				in
				    f_margin75_facts_Table

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

