table f_margin_ytd_data
	lineageTag: 6c2a284b-a6ed-4b7d-b5ae-1395dbd39200

	column time_id
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: 01bece29-1827-4711-8262-48b63f56fafc
		summarizeBy: none
		sourceColumn: time_id

		annotation SummarizationSetBy = Automatic

	column comp_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 148653f4-11fa-47b9-899c-f0242d6fb05a
		summarizeBy: sum
		sourceColumn: comp_id

		annotation SummarizationSetBy = Automatic

	column cust_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 7d5b39c2-be92-47bd-bbe1-ef2130b79c20
		summarizeBy: none
		sourceColumn: cust_id

		annotation SummarizationSetBy = Automatic

	column prod_inv_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2bc44d91-d33b-41bc-a99a-02e3a41478c6
		summarizeBy: none
		sourceColumn: prod_inv_id

		annotation SummarizationSetBy = Automatic

	column mnf_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 78dd1648-cd4e-4a1e-9797-eed6733b8ca4
		summarizeBy: sum
		sourceColumn: mnf_id

		annotation SummarizationSetBy = Automatic

	column org_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 926d90f7-1b94-4b9d-9990-de6cfa01e0a6
		summarizeBy: sum
		sourceColumn: org_id

		annotation SummarizationSetBy = Automatic

	column team_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ee90b25f-e50a-4ad0-89c9-74d3865cfe40
		summarizeBy: none
		sourceColumn: team_id

		annotation SummarizationSetBy = Automatic

	column d_term_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 433e5f42-0e85-49e6-80a8-06300836d0bd
		summarizeBy: sum
		sourceColumn: d_term_id

		annotation SummarizationSetBy = Automatic

	column comp_cost_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 340422f0-5287-458a-98cd-f42d982ae733
		summarizeBy: none
		sourceColumn: comp_cost_id

		annotation SummarizationSetBy = Automatic

	column pricelist_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 3748770e-3b16-45bb-a042-0fafd0a9ee6d
		summarizeBy: sum
		sourceColumn: pricelist_id

		annotation SummarizationSetBy = Automatic

	column src_alo_table
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 2d3bd17e-e408-4d3c-ab15-9a23ee0032a5
		summarizeBy: none
		sourceColumn: src_alo_table

		annotation SummarizationSetBy = Automatic

	column src_info
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: ff289680-16ba-4e21-a3ad-43e882032bd4
		summarizeBy: none
		sourceColumn: src_info

		annotation SummarizationSetBy = Automatic

	column src_row_path
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 4eb17eeb-c89f-412a-b51c-f9c1b6f45669
		summarizeBy: none
		sourceColumn: src_row_path

		annotation SummarizationSetBy = Automatic

	column src_row_path_phase_step
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 00e1f9fd-6a6f-4cb0-b521-832fdc7b2613
		summarizeBy: none
		sourceColumn: src_row_path_phase_step

		annotation SummarizationSetBy = Automatic

	column src_hash
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: d3c5549a-2846-452f-9ac8-ef1c3fd19b73
		summarizeBy: none
		sourceColumn: src_hash

		annotation SummarizationSetBy = Automatic

	column src_phase
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 8f831a9f-d9cd-4d18-9f8e-d4710d958c20
		summarizeBy: none
		sourceColumn: src_phase

		annotation SummarizationSetBy = Automatic

	column src_step
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: b6578e41-9e3a-4fc8-9d4f-76682f2e49c6
		summarizeBy: none
		sourceColumn: src_step

		annotation SummarizationSetBy = Automatic

	column sale_qty
		dataType: double
		sourceProviderType: double
		lineageTag: fe74e468-b675-4a5a-88b9-e1f487936e62
		summarizeBy: sum
		sourceColumn: sale_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_pln_net
		dataType: double
		sourceProviderType: double
		lineageTag: 8ecaad2c-d11e-4a82-a701-94905eea3030
		summarizeBy: sum
		sourceColumn: s_pln_net

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_eur_net
		dataType: double
		sourceProviderType: double
		lineageTag: f155cf06-b961-4034-b8d7-872905c1449b
		summarizeBy: sum
		sourceColumn: s_eur_net

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_pln_corp_cost
		dataType: double
		sourceProviderType: double
		lineageTag: ed334a08-eef5-417f-90a2-d53890fd9a7f
		summarizeBy: sum
		sourceColumn: s_pln_corp_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_eur_corp_cost
		dataType: double
		sourceProviderType: double
		lineageTag: 2a9450cf-a5a8-4369-b99a-5f74f646d84a
		summarizeBy: sum
		sourceColumn: s_eur_corp_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_lic
		dataType: double
		sourceProviderType: double
		lineageTag: d72976a1-d104-4984-a5c1-d81f0d32da42
		summarizeBy: sum
		sourceColumn: c_pln_lic

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_lic
		dataType: double
		sourceProviderType: double
		lineageTag: f00d0426-95ec-4f8d-b5c3-b3f6187fd02f
		summarizeBy: sum
		sourceColumn: c_eur_lic

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_pln_base
		dataType: double
		sourceProviderType: double
		lineageTag: 3c1222d6-b286-4295-82e0-47b6020299e9
		summarizeBy: sum
		sourceColumn: s_pln_base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_eur_base
		dataType: double
		sourceProviderType: double
		lineageTag: 33f1bfea-e5e9-4bda-b30f-6c1fd0150fcf
		summarizeBy: sum
		sourceColumn: s_eur_base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_comm
		dataType: double
		sourceProviderType: double
		lineageTag: 9a67487f-9f25-4e4c-83d3-49ef3a24615f
		summarizeBy: sum
		sourceColumn: c_pln_comm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_comm
		dataType: double
		sourceProviderType: double
		lineageTag: 7cd4381c-ed26-4f1d-bd4b-10df3ee91714
		summarizeBy: sum
		sourceColumn: c_eur_comm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_varfixed
		dataType: double
		sourceProviderType: double
		lineageTag: b3ce7ccd-be1f-4d63-b601-9d399d016735
		summarizeBy: sum
		sourceColumn: c_pln_varfixed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_varfixed
		dataType: double
		sourceProviderType: double
		lineageTag: 6fe780d0-2844-4722-b05e-645b1f1ada74
		summarizeBy: sum
		sourceColumn: c_eur_varfixed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_transport
		dataType: double
		sourceProviderType: double
		lineageTag: 41af039d-0a43-4afc-89ef-395065d03666
		summarizeBy: sum
		sourceColumn: c_pln_transport

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_transport
		dataType: double
		sourceProviderType: double
		lineageTag: 064bd5a6-f18c-427b-a282-f0e676857541
		summarizeBy: sum
		sourceColumn: c_eur_transport

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_compl_prod
		dataType: double
		sourceProviderType: double
		lineageTag: a2a2725d-f7df-45f9-8ae2-806ebd9543d6
		summarizeBy: sum
		sourceColumn: c_pln_compl_prod

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_compl_prod
		dataType: double
		sourceProviderType: double
		lineageTag: 8ba094ed-f2d4-4481-80ca-cdf50271f037
		summarizeBy: sum
		sourceColumn: c_eur_compl_prod

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_sinsuran
		dataType: double
		sourceProviderType: double
		lineageTag: 38438eb4-b598-4cbb-b726-107040426c0b
		summarizeBy: sum
		sourceColumn: c_pln_sinsuran

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_sinsuran
		dataType: double
		sourceProviderType: double
		lineageTag: aee1556d-5a08-4407-8bbf-29f93a4bde42
		summarizeBy: sum
		sourceColumn: c_eur_sinsuran

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_assembly
		dataType: double
		sourceProviderType: double
		lineageTag: 8e3d263f-1e5c-496d-990b-9031eae9bb3f
		summarizeBy: sum
		sourceColumn: c_pln_assembly

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_assembly
		dataType: double
		sourceProviderType: double
		lineageTag: 6df51013-50af-441e-af62-08f685944176
		summarizeBy: sum
		sourceColumn: c_eur_assembly

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_stock_deprec
		dataType: double
		sourceProviderType: double
		lineageTag: 72dcd062-4588-47fd-94db-75311eaac824
		summarizeBy: sum
		sourceColumn: c_pln_stock_deprec

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_stock_deprec
		dataType: double
		sourceProviderType: double
		lineageTag: ba182bda-e403-41ac-b18f-aa3bac848fba
		summarizeBy: sum
		sourceColumn: c_eur_stock_deprec

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_pln_compl_act
		dataType: double
		sourceProviderType: double
		lineageTag: 1dc92479-252e-4e32-a74f-1e997c3cda2a
		summarizeBy: sum
		sourceColumn: c_pln_compl_act

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column c_eur_compl_act
		dataType: double
		sourceProviderType: double
		lineageTag: a3a974a5-e19d-49ba-bf1d-8e070f20654c
		summarizeBy: sum
		sourceColumn: c_eur_compl_act

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hash_key
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 84dd35d7-bf6d-4511-8d70-3bb6397222d5
		summarizeBy: none
		sourceColumn: hash_key

		annotation SummarizationSetBy = Automatic

	column etl_timestamp
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: af9cd9ac-4857-462e-b63f-6a3b38025e3d
		summarizeBy: none
		sourceColumn: etl_timestamp

		annotation SummarizationSetBy = Automatic

	partition f_margin_ytd_data = m
		mode: directQuery
		source = ```
				Value.NativeQuery(
				    Databricks.Catalogs(
				        "adb-16306551450739.19.azuredatabricks.net",
				        "/sql/1.0/warehouses/d77ff9935cb3e9fe",
				        [Catalog="zenith", Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null, MetricViewBiCompatibilityMode=null]
				    ){[Name="zenith",Kind="Database"]}[Data],
				    "
				    SELECT *
				        EXCEPT (
				            `etl_comment`, `mon_name`, `comp_code`, `cust_code`, `prod_si_code`, 
				            `sman_code`, `team_code`, `dept_code`, `d_term_code`, `comp_cost_code`
				        )
				        FROM `zenith`.`mmo75`.`f_margin_ytd_data`
				        WHERE time_id >= 302
				    -- M-2023-01
				    ",
				    null,
				    [EnableFolding=true]
				    )
				
				
				
				
				
				
				// let
				//     Source = Databricks.Catalogs("adb-16306551450739.19.azuredatabricks.net", "/sql/1.0/warehouses/d77ff9935cb3e9fe", [Catalog="zenith", Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null, MetricViewBiCompatibilityMode=null]),
				//     zenith_Database = Source{[Name="zenith",Kind="Database"]}[Data],
				//     mmo75_Schema = zenith_Database{[Name="mmo75",Kind="Schema"]}[Data],
				//     f_margin_ytd_data_Table = mmo75_Schema{[Name="f_margin_ytd_data",Kind="Table"]}[Data],
				//     #"Removed Columns" = Table.RemoveColumns(f_margin_ytd_data_Table,{"etl_comment", "mon_name", "comp_code", "cust_code", "prod_si_code", "sman_code", "team_code", "dept_code", "d_term_code", "comp_cost_code"})
				// in
				//     #"Removed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

