table d_gl_project
	lineageTag: a9299668-eef6-4489-8791-58ebfdfc51fd

	column prj_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: a7209bb2-ae6d-4547-9270-fe06ce9b668d
		summarizeBy: none
		sourceColumn: prj_id

		annotation SummarizationSetBy = Automatic

	column comp_code
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 0c8398e7-c277-4663-bded-1b56411a4444
		summarizeBy: none
		sourceColumn: comp_code

		annotation SummarizationSetBy = Automatic

	column prj_code
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: e957495b-f3ef-49aa-b54d-b45d9b5b063b
		summarizeBy: none
		sourceColumn: prj_code

		annotation SummarizationSetBy = Automatic

	column prj_desc
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: a43c5151-dbc1-4a24-877a-8df10b1cc749
		summarizeBy: none
		sourceColumn: prj_desc

		annotation SummarizationSetBy = Automatic

	column prj_sgrp_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 5ecd4b42-c7d1-4be9-b83e-72d72edfdfc5
		summarizeBy: sum
		sourceColumn: prj_sgrp_id

		annotation SummarizationSetBy = Automatic

	column prj_sgrp_code
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 99dbbf83-ce46-47d9-8129-741d4d1e4939
		summarizeBy: none
		sourceColumn: prj_sgrp_code

		annotation SummarizationSetBy = Automatic

	column prj_sgrp_name
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 4de0fa49-d3ab-4ab2-8ac7-4c6b2dc8b477
		summarizeBy: none
		sourceColumn: prj_sgrp_name

		annotation SummarizationSetBy = Automatic

	column prj_grp_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 1a95d926-4ad0-4afc-95ad-fd275381ed08
		summarizeBy: sum
		sourceColumn: prj_grp_id

		annotation SummarizationSetBy = Automatic

	column prj_grp_code
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 44bcf10a-13e2-4ba1-b491-424d6d0342b7
		summarizeBy: none
		sourceColumn: prj_grp_code

		annotation SummarizationSetBy = Automatic

	column prj_grp_name
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 42fa81f6-d971-4745-b54c-152800107db0
		summarizeBy: none
		sourceColumn: prj_grp_name

		annotation SummarizationSetBy = Automatic

	column owner_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 500d33a1-1862-4927-9a32-b73f1e093abc
		summarizeBy: sum
		sourceColumn: owner_id

		annotation SummarizationSetBy = Automatic

	column owner_code
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: e938dd53-6d26-4e03-9f51-3884f0e59cc1
		summarizeBy: none
		sourceColumn: owner_code

		annotation SummarizationSetBy = Automatic

	column owner_name
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: ca9d8677-f109-485a-bfd2-84fbd91bbb0c
		summarizeBy: none
		sourceColumn: owner_name

		annotation SummarizationSetBy = Automatic

	column front_office
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 82fee41d-c489-4505-98ec-4181540b8d18
		summarizeBy: none
		sourceColumn: front_office

		annotation SummarizationSetBy = Automatic

	column project_manager
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 738664ae-933a-4328-8734-53b9a27953a6
		summarizeBy: none
		sourceColumn: project_manager

		annotation SummarizationSetBy = Automatic

	column coordinator_bo
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: b192a1ac-f3eb-4319-afa4-388dcc283737
		summarizeBy: none
		sourceColumn: coordinator_bo

		annotation SummarizationSetBy = Automatic

	column mpk_code
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 23474ef6-49e9-4dfc-a767-5d4643613a18
		summarizeBy: none
		sourceColumn: mpk_code

		annotation SummarizationSetBy = Automatic

	column hprj_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 7b5ca404-4609-4fcd-8068-5b899be1a812
		summarizeBy: sum
		sourceColumn: hprj_id

		annotation SummarizationSetBy = Automatic

	column hprj_code
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: cc1c0374-f9ae-4ad7-8107-290a17f83b0e
		summarizeBy: none
		sourceColumn: hprj_code

		annotation SummarizationSetBy = Automatic

	partition d_gl_project = m
		mode: directQuery
		source =
				let
				    Źródło = Databricks.Catalogs("adb-16306551450739.19.azuredatabricks.net", "/sql/1.0/warehouses/d77ff9935cb3e9fe", null),
				    zenith_Database = Źródło{[Name="zenith",Kind="Database"]}[Data],
				    edw_Schema = zenith_Database{[Name="edw",Kind="Schema"]}[Data],
				    d_gl_project_View = edw_Schema{[Name="d_gl_project",Kind="View"]}[Data],
				    #"Usunięto kolumny" = Table.RemoveColumns(d_gl_project_View,{"record_source", "record_version", "first_load_date", "last_seen_date", "source_exist", "db_code"}),
				    #"Przefiltrowano wiersze" = Table.SelectRows(#"Usunięto kolumny", each Text.StartsWith([prj_code], "W-2"))
				in
				    #"Przefiltrowano wiersze"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

