table f_capex_imp_cost_data
	lineageTag: 3f0f7429-95ef-48b6-81a1-d3e5bb9f8fa3

	column time_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: d309ab67-78c1-4098-aec3-cec44342a12e
		summarizeBy: sum
		sourceColumn: time_id

		annotation SummarizationSetBy = Automatic

	column mpk_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 502d6095-2c65-4096-aa8b-dd56cafb483d
		summarizeBy: sum
		sourceColumn: mpk_id

		annotation SummarizationSetBy = Automatic

	column account_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 830fa685-fed7-4838-b337-ccacc889b88b
		summarizeBy: sum
		sourceColumn: account_id

		annotation SummarizationSetBy = Automatic

	column pay_account_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2da7e227-3dbb-4ff1-a57d-51c6187df3f3
		summarizeBy: sum
		sourceColumn: pay_account_id

		annotation SummarizationSetBy = Automatic

	column cost_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: b965d3c5-f000-45f3-9795-05516f2e4911
		summarizeBy: sum
		sourceColumn: cost_id

		annotation SummarizationSetBy = Automatic

	column prj_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 5eac4e1f-9689-41c8-8f14-809f07ed4fe0
		summarizeBy: none
		sourceColumn: prj_id

		annotation SummarizationSetBy = Automatic

	column supp_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: b7e346af-f930-4016-ab03-9c58b0b0fef7
		summarizeBy: sum
		sourceColumn: supp_id

		annotation SummarizationSetBy = Automatic

	column curr_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 354d7fd2-33dd-42bd-beff-c37cbfc7cc37
		summarizeBy: sum
		sourceColumn: curr_id

		annotation SummarizationSetBy = Automatic

	column fin_curr_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e1437f0b-7864-48da-9925-5172edbd5a0d
		summarizeBy: sum
		sourceColumn: fin_curr_id

		annotation SummarizationSetBy = Automatic

	column comp_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: cb049046-dacb-42a0-94f8-558578453529
		summarizeBy: sum
		sourceColumn: comp_id

		annotation SummarizationSetBy = Automatic

	column var_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e91c258b-1f24-49d1-a33d-4a3c4234a233
		summarizeBy: sum
		sourceColumn: var_id

		annotation SummarizationSetBy = Automatic

	column voucher_type_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 42bc8872-abe0-4046-a440-059cab155b83
		summarizeBy: sum
		sourceColumn: voucher_type_id

		annotation SummarizationSetBy = Automatic

	column prior_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: fe05f0ac-ad66-4cb7-95b8-1dcc7f344068
		summarizeBy: sum
		sourceColumn: prior_id

		annotation SummarizationSetBy = Automatic

	column ccat_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 1ebed10d-c9fb-4946-b56c-108fd13873ac
		summarizeBy: sum
		sourceColumn: ccat_id

		annotation SummarizationSetBy = Automatic

	column debet_amount_pln
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: 83e8ffda-6b2b-4edc-bdbe-756db9993a3a
		summarizeBy: sum
		sourceColumn: debet_amount_pln

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column credit_amount_pln
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: a73300e7-c1f4-47ca-8ab1-87cf1644e8f8
		summarizeBy: sum
		sourceColumn: credit_amount_pln

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column amount_pln
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: 4ddc53c7-6790-4650-853f-adb7ef71341c
		summarizeBy: sum
		sourceColumn: amount_pln

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column debet_amount_bpln
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: b5221a11-7fca-4a72-92f1-4c6e97b47e1f
		summarizeBy: sum
		sourceColumn: debet_amount_bpln

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column credit_amount_bpln
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: b9ee12c7-c254-41e9-8e4a-2a84032a8982
		summarizeBy: sum
		sourceColumn: credit_amount_bpln

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column amount_bpln
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: 4eb2d215-7679-4a90-8172-6f31b9f834dd
		summarizeBy: sum
		sourceColumn: amount_bpln

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column debet_amount_eur
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: f4183b15-6ee3-44bf-b6fe-c0d01dfa9b66
		summarizeBy: sum
		sourceColumn: debet_amount_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column credit_amount_eur
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: 762cf948-3203-457d-9802-c510f59cb872
		summarizeBy: sum
		sourceColumn: credit_amount_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column amount_eur
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: 37af7a93-b7d0-4298-b54f-a7ad33b030a7
		summarizeBy: sum
		sourceColumn: amount_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column debet_amount_beur
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: 6010a072-a466-4884-a327-9089a3d35d61
		summarizeBy: sum
		sourceColumn: debet_amount_beur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column credit_amount_beur
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: 71a7206b-9f4b-45b7-9491-cfdc8fe73c46
		summarizeBy: sum
		sourceColumn: credit_amount_beur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column amount_beur
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: 5596fe59-5ed8-477e-90fc-130171e58c0a
		summarizeBy: sum
		sourceColumn: amount_beur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column debet_amount_cur
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: f92bcfb4-005e-471e-8000-2f40586f9104
		summarizeBy: sum
		sourceColumn: debet_amount_cur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column credit_amount_cur
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: 9eb15e4d-c519-4dec-b7b4-ab57b14a5441
		summarizeBy: sum
		sourceColumn: credit_amount_cur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column amount_cur
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: cf83bce4-9ee1-4e21-aa7c-bb60757d39f5
		summarizeBy: sum
		sourceColumn: amount_cur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column debet_amount_fcur
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: 86ced1f2-d051-4c7b-8ada-94817c688bd0
		summarizeBy: sum
		sourceColumn: debet_amount_fcur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column credit_amount_fcur
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: 04f7ce02-9bfe-4069-8492-f5ac2772c7c9
		summarizeBy: sum
		sourceColumn: credit_amount_fcur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column amount_fcur
		dataType: double
		sourceProviderType: decimal(38, 18)
		lineageTag: 9f651ce6-1e52-4fa6-87f4-809c44035040
		summarizeBy: sum
		sourceColumn: amount_fcur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bi
		dataType: int64
		formatString: 0
		sourceProviderType: tinyint
		lineageTag: cc687bbd-5b0d-4790-bc58-11f0fe19db75
		summarizeBy: sum
		sourceColumn: bi

		annotation SummarizationSetBy = Automatic

	column wfd_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: a780ac88-d81a-4f6f-9766-9800965156b9
		summarizeBy: sum
		sourceColumn: wfd_id

		annotation SummarizationSetBy = Automatic

	column link
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 9ab07967-5943-4da5-b3c5-06017bc8f0c9
		summarizeBy: none
		sourceColumn: link

		annotation SummarizationSetBy = Automatic

	column ccat_rule_list
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 2f540704-65db-4d3a-b94c-e13ef4cbee5b
		summarizeBy: none
		sourceColumn: ccat_rule_list

		annotation SummarizationSetBy = Automatic

	column ccat_rule_cnt
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 07299f20-89b2-4e51-b74d-5d86cee37472
		summarizeBy: sum
		sourceColumn: ccat_rule_cnt

		annotation SummarizationSetBy = Automatic

	column src_rule_no
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 1142df04-b6aa-4a6e-93f6-9e126598b3ac
		summarizeBy: none
		sourceColumn: src_rule_no

		annotation SummarizationSetBy = Automatic

	column src_db_code
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 70e001c4-9cc4-4d0c-8c0c-161f6e95add7
		summarizeBy: none
		sourceColumn: src_db_code

		annotation SummarizationSetBy = Automatic

	column src_db_code_2
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: a3acffaf-5392-4bb4-87b9-b9df15a1ee8d
		summarizeBy: none
		sourceColumn: src_db_code_2

		annotation SummarizationSetBy = Automatic

	column src_company
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: cf51655a-6992-4d10-a469-95cb72834306
		summarizeBy: none
		sourceColumn: src_company

		annotation SummarizationSetBy = Automatic

	column src_gl_company
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: b41961f3-dff5-4e9e-a5d8-958061ab481f
		summarizeBy: none
		sourceColumn: src_gl_company

		annotation SummarizationSetBy = Automatic

	column src_year_period_key
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 149c08aa-3cfb-4535-9cc0-269b035d7fc3
		summarizeBy: sum
		sourceColumn: src_year_period_key

		annotation SummarizationSetBy = Automatic

	column src_voucher_date
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 6560c1d5-4063-4263-ab60-9dabdab7cd31
		summarizeBy: none
		sourceColumn: src_voucher_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column src_voucher_type
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: dc33a839-c37c-4923-8171-8ac55d5dd2df
		summarizeBy: none
		sourceColumn: src_voucher_type

		annotation SummarizationSetBy = Automatic

	column src_voucher_no
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: ea91e0e5-d273-409e-a7c8-c76b7099d282
		summarizeBy: sum
		sourceColumn: src_voucher_no

		annotation SummarizationSetBy = Automatic

	column src_event_date
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 71bf7ef9-ad7f-436a-98d8-878eedc845bd
		summarizeBy: none
		sourceColumn: src_event_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column src_doc_date
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: c4c91e1e-a7b5-406a-be80-297d18c92043
		summarizeBy: none
		sourceColumn: src_doc_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column src_reference_number
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 315ca44d-9ccc-4b04-908a-93e9183e5ec6
		summarizeBy: none
		sourceColumn: src_reference_number

		annotation SummarizationSetBy = Automatic

	column src_reference_row_no
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: be78081e-6e9a-46a7-be66-f59888b081d7
		summarizeBy: sum
		sourceColumn: src_reference_row_no

		annotation SummarizationSetBy = Automatic

	column src_reference_serie
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: c26c2fbf-82bc-4581-a791-36fe03059c30
		summarizeBy: none
		sourceColumn: src_reference_serie

		annotation SummarizationSetBy = Automatic

	column src_account
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: eeb0b080-c351-48c2-bae9-8be3ee80e4f1
		summarizeBy: none
		sourceColumn: src_account

		annotation SummarizationSetBy = Automatic

	column src_code_b
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 2a57dfbb-d9fe-41ca-93b7-996d27cee953
		summarizeBy: none
		sourceColumn: src_code_b

		annotation SummarizationSetBy = Automatic

	column src_code_c
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 3a520db2-6436-4c1e-807c-402fe6a8b2bf
		summarizeBy: none
		sourceColumn: src_code_c

		annotation SummarizationSetBy = Automatic

	column src_code_d
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 38730289-f0f1-4166-8161-0dbec40a8789
		summarizeBy: none
		sourceColumn: src_code_d

		annotation SummarizationSetBy = Automatic

	column src_code_e
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: e5a529c3-3dc8-449f-9e5e-3f830a1f7b19
		summarizeBy: none
		sourceColumn: src_code_e

		annotation SummarizationSetBy = Automatic

	column src_code_f
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 45191f6e-4bd3-4a79-9d7a-0f9252750720
		summarizeBy: none
		sourceColumn: src_code_f

		annotation SummarizationSetBy = Automatic

	column src_code_g
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: a53aa93a-0040-41a7-a862-7408dc7d829e
		summarizeBy: none
		sourceColumn: src_code_g

		annotation SummarizationSetBy = Automatic

	column src_code_g_description
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: c840d9d5-7374-4aee-bb65-399ea444ff97
		summarizeBy: none
		sourceColumn: src_code_g_description

		annotation SummarizationSetBy = Automatic

	column src_code_h
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 33acf3ef-49e7-4616-b33f-e9cddbe2af10
		summarizeBy: none
		sourceColumn: src_code_h

		annotation SummarizationSetBy = Automatic

	column src_code_i
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 435ac12b-a50e-4a6e-aa15-4bcc5e3e332a
		summarizeBy: none
		sourceColumn: src_code_i

		annotation SummarizationSetBy = Automatic

	column src_code_j
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: f63a5d80-71ea-4ec5-895b-eebfc89b5136
		summarizeBy: none
		sourceColumn: src_code_j

		annotation SummarizationSetBy = Automatic

	column src_party_type_id
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 174fea5c-bd30-439c-ad26-e9182b8af1fa
		summarizeBy: none
		sourceColumn: src_party_type_id

		annotation SummarizationSetBy = Automatic

	column src_currency_code
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: a2f477eb-dc2d-4c1e-b411-d51ea634b64b
		summarizeBy: none
		sourceColumn: src_currency_code

		annotation SummarizationSetBy = Automatic

	column src_dom_currency_code
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 2a502785-04c0-48d7-984a-fb5c2a34190c
		summarizeBy: none
		sourceColumn: src_dom_currency_code

		annotation SummarizationSetBy = Automatic

	column src_company_currency_code
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: c3f3ab0c-d320-4ff3-857b-526e0b2518b2
		summarizeBy: none
		sourceColumn: src_company_currency_code

		annotation SummarizationSetBy = Automatic

	column src_text
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: e417a181-2e6c-4c56-9132-aad1c618814f
		summarizeBy: none
		sourceColumn: src_text

		annotation SummarizationSetBy = Automatic

	column src_variant
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: f792d669-797d-4a4d-8570-84f3f92ef62e
		summarizeBy: none
		sourceColumn: src_variant

		annotation SummarizationSetBy = Automatic

	column src_trans_code
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 200f27aa-96a5-4438-b895-0df2afaa4729
		summarizeBy: none
		sourceColumn: src_trans_code

		annotation SummarizationSetBy = Automatic

	column src_payment_account
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: ba2d99e4-4ccd-414f-8f5e-f013599de61d
		summarizeBy: none
		sourceColumn: src_payment_account

		annotation SummarizationSetBy = Automatic

	column src_mixed_payment_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 77663416-20d4-4e3b-835d-7c0dec4aebf7
		summarizeBy: sum
		sourceColumn: src_mixed_payment_id

		annotation SummarizationSetBy = Automatic

	column src_mixed_payment_id_cnt
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ec528cd6-ef49-4e01-86e7-1ba34177a6bd
		summarizeBy: sum
		sourceColumn: src_mixed_payment_id_cnt

		annotation SummarizationSetBy = Automatic

	column src_mixed_payment_date
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: a15b0d8d-054a-460b-bc2b-213ce5b0964e
		summarizeBy: none
		sourceColumn: src_mixed_payment_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column src_voucher_type_ref
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 688fe7b0-9310-4340-bc6a-541b255a8fee
		summarizeBy: none
		sourceColumn: src_voucher_type_ref

		annotation SummarizationSetBy = Automatic

	column src_voucher_no_ref
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: eb27553c-2b76-4e61-9a8b-423c1eeaa064
		summarizeBy: sum
		sourceColumn: src_voucher_no_ref

		annotation SummarizationSetBy = Automatic

	column impl_cat_cost_code
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 5884ac78-eb1e-4988-a83e-306e4bd64753
		summarizeBy: none
		sourceColumn: impl_cat_cost_code

		annotation SummarizationSetBy = Automatic

	column impl_cat_cost_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 7700ad67-7b01-4686-88f5-e2b293c2f461
		summarizeBy: none
		sourceColumn: impl_cat_cost_id

		annotation SummarizationSetBy = Automatic

	partition f_capex_imp_cost_data = m
		mode: directQuery
		source =
				let
				    Źródło = Databricks.Catalogs("adb-16306551450739.19.azuredatabricks.net", "/sql/1.0/warehouses/d77ff9935cb3e9fe", null),
				    controlling_Database = Źródło{[Name="controlling",Kind="Database"]}[Data],
				    capex_implement_Schema = controlling_Database{[Name="capex_implement",Kind="Schema"]}[Data],
				    f_capex_imp_cost_data_View = capex_implement_Schema{[Name="f_capex_imp_cost_data",Kind="View"]}[Data],
				    #"Usunięto kolumny" = Table.RemoveColumns(f_capex_imp_cost_data_View,{"record_source", "record_view", "record_version"}),
				    #"Posortowano wiersze" = Table.Sort(#"Usunięto kolumny",{{"time_id", Order.Descending}})
				in
				    #"Posortowano wiersze"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

