table 'Sales Measures'
	lineageTag: c9fcf36a-d8ca-436c-b170-b1117013a37e

	measure 'Catalog Discount PLN' = EXTERNALMEASURE("Catalog Discount PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: f483a975-1850-44be-9f71-f947ea54c161
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Catalog Discount PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Catalog Discount PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Cust Price Discount PLN' = EXTERNALMEASURE("Cust Price Discount PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: d48ea14f-1cc1-4c82-b325-10cab970dfe2
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Cust Price Discount PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Cust Price Discount PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Discount PLN' = EXTERNALMEASURE("Discount PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: a0eeb1f6-73d3-4c85-86b3-2276b7c520f7
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Discount PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Discount PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Curr Norm Margin PLN' = EXTERNALMEASURE("Curr Norm Margin PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: b0bdb42c-3374-4f4e-a181-7c7326a84895
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Curr Norm Margin PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Curr Norm Margin PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Annual Norm Margin PLN' = EXTERNALMEASURE("Annual Norm Margin PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: 60f26f67-5b07-4fcf-85c0-915bcc3bf021
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Annual Norm Margin PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Annual Norm Margin PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Kwdr Unit PLN' = EXTERNALMEASURE("Kwdr Unit PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: 400fdd19-aced-4e62-aedd-0a1e9940eed9
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Kwdr Unit PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Kwdr Unit PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Catalog Discount bPLN' = EXTERNALMEASURE("Catalog Discount bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bPLN
		lineageTag: b3b61cba-7b55-44cf-8af0-f333a8b2c395
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Catalog Discount bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Catalog Discount bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Cust Price Discount bPLN' = EXTERNALMEASURE("Cust Price Discount bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bPLN
		lineageTag: 7448b642-e760-4206-be50-8938cd7b8df6
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Cust Price Discount bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Cust Price Discount bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Discount bPLN' = EXTERNALMEASURE("Discount bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bPLN
		lineageTag: 9822fb2c-30db-4db3-bbec-b1154612efe9
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Discount bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Discount bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Curr Norm Margin bPLN' = EXTERNALMEASURE("Curr Norm Margin bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bPLN
		lineageTag: 4ddfeca4-7131-4603-ac5e-02f4e70fda6c
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Curr Norm Margin bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Curr Norm Margin bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Annual Norm Margin bPLN' = EXTERNALMEASURE("Annual Norm Margin bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bPLN
		lineageTag: e9614a9c-d8a0-4117-9bbe-a51e4c7a33f5
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Annual Norm Margin bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Annual Norm Margin bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'CtrlPLN Margin' = EXTERNALMEASURE("CtrlPLN Margin", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary kontrolingowe CtrlPLN
		lineageTag: c3b7e35a-ece0-4716-b140-1998cd2454c1
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.CtrlPLN Margin
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_CtrlPLN Margin FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'CtrlPLN Budget Margin' = EXTERNALMEASURE("CtrlPLN Budget Margin", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary kontrolingowe CtrlPLN
		lineageTag: 32cb7e83-c888-4cb2-b87c-f8ba71b8d6ac
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.CtrlPLN Budget Margin
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_CtrlPLN Budget Margin FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Catalog Discount EUR' = EXTERNALMEASURE("Catalog Discount EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary holdingowe EUR
		lineageTag: de2f1f3c-bbaf-4050-a1cb-4f8f4924cf1b
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Catalog Discount EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Catalog Discount EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Cust Price Discount EUR' = EXTERNALMEASURE("Cust Price Discount EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary holdingowe EUR
		lineageTag: 0c0f9712-0720-4d44-8326-e453914882d6
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Cust Price Discount EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Cust Price Discount EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Discount EUR' = EXTERNALMEASURE("Discount EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary holdingowe EUR
		lineageTag: 42c4b9b6-cf34-46fe-ab34-7bfd619774c4
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Discount EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Discount EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Curr Norm Margin EUR' = EXTERNALMEASURE("Curr Norm Margin EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary holdingowe EUR
		lineageTag: d806e139-a7ec-46b4-8fc5-783da067c3e6
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Curr Norm Margin EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Curr Norm Margin EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Annual Norm Margin EUR' = EXTERNALMEASURE("Annual Norm Margin EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary holdingowe EUR
		lineageTag: 812bc142-b043-4618-a7f9-28585eb93e60
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Annual Norm Margin EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Annual Norm Margin EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Catalog Discount bEUR' = EXTERNALMEASURE("Catalog Discount bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bEUR
		lineageTag: fb27c0e9-7a97-4429-95fc-9ffe0c5b3c9c
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Catalog Discount bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Catalog Discount bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Cust Price Discount bEUR' = EXTERNALMEASURE("Cust Price Discount bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bEUR
		lineageTag: 89d56ef6-c296-478b-94a3-a3535f606da3
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Cust Price Discount bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Cust Price Discount bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Discount bEUR' = EXTERNALMEASURE("Discount bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bEUR
		lineageTag: cb44322e-1e1f-4921-8356-277988359693
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Discount bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Discount bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Annual Norm Margin bEUR' = EXTERNALMEASURE("Annual Norm Margin bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bEUR
		lineageTag: b1f4407b-7151-46b3-9ed0-c1f33152fa38
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Annual Norm Margin bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Annual Norm Margin bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Group Margin bEUR' = EXTERNALMEASURE("Group Margin bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bEUR
		lineageTag: 5aaa2b8a-0ece-4569-b3de-d6c3a7dcf472
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Group Margin bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Group Margin bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Catalog Discount CUR' = EXTERNALMEASURE("Catalog Discount CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: e466c148-1625-4ec1-bd1f-e7631d9b9767
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Catalog Discount CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Catalog Discount CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Cust Price Discount CUR' = EXTERNALMEASURE("Cust Price Discount CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: 02ca7e7a-4eeb-4915-ad3f-6b9fa25f5999
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Cust Price Discount CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Cust Price Discount CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Discount CUR' = EXTERNALMEASURE("Discount CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: bdd4dba8-b741-4305-92de-220dea3c5a4e
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Discount CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Discount CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Curr Norm Margin CUR' = EXTERNALMEASURE("Curr Norm Margin CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: 1f807e77-a5c0-49b8-a838-5f774db70265
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Curr Norm Margin CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Curr Norm Margin CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Average Product Price CUR' = EXTERNALMEASURE("Average Product Price CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: 5c70615b-132f-4b9b-a41c-752b25e672d3
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Average Product Price CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Average Product Price CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Average Product Price PLN' = EXTERNALMEASURE("Average Product Price PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary wyliczane proste
		lineageTag: c4b31af4-86bc-4227-bc8c-f83cbd3b6f3b
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Average Product Price PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Average Product Price PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Cur to EUR Curr Rate' = EXTERNALMEASURE("Cur to EUR Curr Rate", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary wyliczane proste
		lineageTag: f76b281b-7494-490d-bcca-fe9c01af674a
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Cur to EUR Curr Rate
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Cur to EUR Curr Rate FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Discount %' = EXTERNALMEASURE("Discount %", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary wyliczane proste
		lineageTag: 2eca5132-decb-4aa8-aa57-9e9da2402a1e
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Discount %
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Discount % FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Curr Norm Margin %' = EXTERNALMEASURE("Curr Norm Margin %", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary wyliczane proste
		lineageTag: c553eac7-cc17-4d09-8bf5-133654877daa
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Curr Norm Margin %
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Curr Norm Margin % FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Annual Norm Margin %' = EXTERNALMEASURE("Annual Norm Margin %", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary wyliczane proste
		lineageTag: d21ac83b-3b86-45f0-a385-54a9ee5cf4cb
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Annual Norm Margin %
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Annual Norm Margin % FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Cur to PLN Curr Rate' = EXTERNALMEASURE("Cur to PLN Curr Rate", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary wyliczane proste
		lineageTag: d81c7dd9-9f0a-4fbc-a26c-98eee39ef845
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Cur to PLN Curr Rate
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Cur to PLN Curr Rate FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net Sales PLN YA' = EXTERNALMEASURE("Net Sales PLN YA", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		isHidden
		displayFolder: Miary wyliczane czasowe
		lineageTag: 2784c3da-005f-4e7e-8350-543e6c3e9711
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net Sales PLN YA
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net Sales PLN YA FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net sales EUR YA' = EXTERNALMEASURE("Net sales EUR YA", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		isHidden
		displayFolder: Miary wyliczane czasowe
		lineageTag: 9c02aa71-107a-4f38-b57b-c2472204c274
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net sales EUR YA
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net sales EUR YA FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net sales bEUR YA' = EXTERNALMEASURE("Net sales bEUR YA", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		isHidden
		displayFolder: Miary wyliczane czasowe
		lineageTag: 12316ab3-37aa-44d5-b4fb-f53831b220fa
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net sales bEUR YA
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net sales bEUR YA FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net sales bPLN YA' = EXTERNALMEASURE("Net sales bPLN YA", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		isHidden
		displayFolder: Miary wyliczane czasowe
		lineageTag: a46ef299-ed23-407e-9096-21ec1153798e
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net sales bPLN YA
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net sales bPLN YA FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net sales CUR YA' = EXTERNALMEASURE("Net sales CUR YA", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		isHidden
		displayFolder: Miary wyliczane czasowe
		lineageTag: 2c92d643-25a4-45e0-acf2-1c4bf8b54fdd
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net sales CUR YA
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net sales CUR YA FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net Price (Invent Index) EUR' = EXTERNALMEASURE("Net Price (Invent Index) EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		isHidden
		displayFolder: Miary transakcyjne
		lineageTag: 0cb3afa5-0183-4129-8bf1-85d56f6f29b0
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net Price (Invent Index) EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net Price (Invent Index) EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net sales CtrlPLN YA' = EXTERNALMEASURE("Net sales CtrlPLN YA", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		isHidden
		displayFolder: Miary kontrolingowe CtrlPLN YA
		lineageTag: c4726436-d08a-4c54-a3bf-9545698fc42c
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net sales CtrlPLN YA
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net sales CtrlPLN YA FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Annual Norm Cost PLN' = EXTERNALMEASURE("Annual Norm Cost PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: f3ce32e3-4057-4815-bc13-ff16546ea104
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Annual Norm Cost PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Annual Norm Cost PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Base Sales PLN' = EXTERNALMEASURE("Base Sales PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: aabc9177-2f1a-4628-8e72-0199b60efbc3
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Base Sales PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Base Sales PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Catalog Sales PLN' = EXTERNALMEASURE("Catalog Sales PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: 0b539c43-5943-4dcc-a7c0-8f50d069cdb6
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Catalog Sales PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Catalog Sales PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Curr Norm Cost PLN' = EXTERNALMEASURE("Curr Norm Cost PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: bd305183-4bf2-49ed-9afa-d765db8e7028
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Curr Norm Cost PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Curr Norm Cost PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Cust Price Sales PLN' = EXTERNALMEASURE("Cust Price Sales PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: 5049f72a-dd1c-4da0-bb41-39befc205819
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Cust Price Sales PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Cust Price Sales PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Inventory Quantity' = EXTERNALMEASURE("Inventory Quantity", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: 67325b36-2a60-4117-9323-b28ae4aa0710
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Inventory Quantity
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Inventory Quantity FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Kwdr PLN' = EXTERNALMEASURE("Kwdr PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: 29fd87d4-cc9e-4547-b2f0-e38af3cbfa8b
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Kwdr PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Kwdr PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Manufacturing Cost PLN' = EXTERNALMEASURE("Manufacturing Cost PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: 43df4df3-d632-4fff-9df5-d04559205152
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Manufacturing Cost PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Manufacturing Cost PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net Sales PLN' = EXTERNALMEASURE("Net Sales PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: 229bbcce-69a0-4ed8-b2c7-8be03057ac9c
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net Sales PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net Sales PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Sales Quantity' = EXTERNALMEASURE("Sales Quantity", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: 6d4b81e6-7b6e-4d5d-a6e0-aa69428b0029
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Sales Quantity
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Sales Quantity FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Annual Norm Cost bPLN' = EXTERNALMEASURE("Annual Norm Cost bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bPLN
		lineageTag: 24d7a773-bd19-4ce8-b043-36a9c8ef67d2
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Annual Norm Cost bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Annual Norm Cost bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Annual Norm Cost EUR' = EXTERNALMEASURE("Annual Norm Cost EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary holding EUR
		lineageTag: 033b7130-4639-4bbc-b62f-eb609031fb44
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Annual Norm Cost EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Annual Norm Cost EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Annual Norm Cost bEUR' = EXTERNALMEASURE("Annual Norm Cost bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bEUR
		lineageTag: cee99297-5efe-4812-8686-882e0f0926e2
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Annual Norm Cost bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Annual Norm Cost bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Annual Norm Cost CUR' = EXTERNALMEASURE("Annual Norm Cost CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: 6796c185-b820-4e80-ab60-5d91ecb988b3
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Annual Norm Cost CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Annual Norm Cost CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Annual Norm Cost CtrlPLN' = EXTERNALMEASURE("Annual Norm Cost CtrlPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary kontrolingowe CtrlPLN
		lineageTag: ea8eaf57-ecc1-4c4c-83a9-e9023d42af31
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Annual Norm Cost CtrlPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Annual Norm Cost CtrlPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Base Sales bPLN' = EXTERNALMEASURE("Base Sales bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bPLN
		lineageTag: 073c86dd-392b-406a-91d5-99283965380f
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Base Sales bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Base Sales bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Base Sales EUR' = EXTERNALMEASURE("Base Sales EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary holding EUR
		lineageTag: 981c6098-c18d-4ed2-a08b-ac98004ec67a
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Base Sales EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Base Sales EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Base Sales bEUR' = EXTERNALMEASURE("Base Sales bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bEUR
		lineageTag: d61c2e0b-3f64-463a-b4a6-76bf1ce11fa5
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Base Sales bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Base Sales bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Base Sales CUR' = EXTERNALMEASURE("Base Sales CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: 4198d3a7-58c4-4bc7-a21a-f7ec72e9ec1d
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Base Sales CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Base Sales CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Base Sales CtrlPLN' = EXTERNALMEASURE("Base Sales CtrlPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary kontrolingowe CtrlPLN
		lineageTag: 36c94c1c-c282-4e00-b05d-621d1702fc63
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Base Sales CtrlPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Base Sales CtrlPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Catalog Sales bPLN' = EXTERNALMEASURE("Catalog Sales bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bPLN
		lineageTag: 51f9ec2c-c534-4ff5-8be7-c2fb6a1818e3
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Catalog Sales bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Catalog Sales bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Catalog Sales EUR' = EXTERNALMEASURE("Catalog Sales EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary holding EUR
		lineageTag: db84fd3b-bf08-4db3-b383-b622f08ea0da
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Catalog Sales EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Catalog Sales EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Catalog Sales bEUR' = EXTERNALMEASURE("Catalog Sales bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bEUR
		lineageTag: 2c29f97d-843b-45e7-9fd8-66372a75464c
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Catalog Sales bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Catalog Sales bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Catalog Sales CUR' = EXTERNALMEASURE("Catalog Sales CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: dcefc134-a300-4dcc-9e20-c07762112120
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Catalog Sales CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Catalog Sales CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Catalog Sales CtrlPLN' = EXTERNALMEASURE("Catalog Sales CtrlPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary kontrolingowe CtrlPLN
		lineageTag: 2af5e492-ee05-4de2-87c2-3ff3c2ca07c3
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Catalog Sales CtrlPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Catalog Sales CtrlPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Curr Norm Cost bPLN' = EXTERNALMEASURE("Curr Norm Cost bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bPLN
		lineageTag: 5afa2746-9792-46c2-a2d5-feb0ac49c622
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Curr Norm Cost bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Curr Norm Cost bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Curr Norm Cost EUR' = EXTERNALMEASURE("Curr Norm Cost EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary holding EUR
		lineageTag: 4472c9e4-2b21-4830-8bce-cd26150006f3
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Curr Norm Cost EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Curr Norm Cost EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Curr Norm Cost bEUR' = EXTERNALMEASURE("Curr Norm Cost bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bEUR
		lineageTag: 5614304f-fd9f-407d-9411-51a4d6229c36
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Curr Norm Cost bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Curr Norm Cost bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Curr Norm Cost CUR' = EXTERNALMEASURE("Curr Norm Cost CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: dc503cb6-c7d0-4bab-b89b-f6a59e10c489
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Curr Norm Cost CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Curr Norm Cost CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Curr Norm Cost CtrlPLN' = EXTERNALMEASURE("Curr Norm Cost CtrlPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary kontrolingowe CtrlPLN
		lineageTag: e5f1a822-b5b2-4e1d-a2a9-7778d5ac9414
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Curr Norm Cost CtrlPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Curr Norm Cost CtrlPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Curr Norm Cost CUR Dom' = EXTERNALMEASURE("Curr Norm Cost CUR Dom", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: e7885eb8-3ba5-44f1-9950-eaaaa82d7379
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Curr Norm Cost CUR Dom
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Curr Norm Cost CUR Dom FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Cust Price Sales bPLN' = EXTERNALMEASURE("Cust Price Sales bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bPLN
		lineageTag: 39643938-8641-4681-a01b-8a77a9fde40e
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Cust Price Sales bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Cust Price Sales bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Cust Price Sales EUR' = EXTERNALMEASURE("Cust Price Sales EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary holding EUR
		lineageTag: 1d4c6bdf-8512-4651-9fab-c621923b66c5
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Cust Price Sales EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Cust Price Sales EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Cust Price Sales bEUR' = EXTERNALMEASURE("Cust Price Sales bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bEUR
		lineageTag: 88323cab-f7be-44b1-9213-9cf165a4ff5a
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Cust Price Sales bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Cust Price Sales bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Cust Price Sales CUR' = EXTERNALMEASURE("Cust Price Sales CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: a1faf439-ceff-48b4-b9f3-345fe94f29a0
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Cust Price Sales CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Cust Price Sales CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Cust Price Sales CtrlPLN' = EXTERNALMEASURE("Cust Price Sales CtrlPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary kontrolingowe CtrlPLN
		lineageTag: e9aad2c2-b06f-4c45-be55-c9a7a77614e7
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Cust Price Sales CtrlPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Cust Price Sales CtrlPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net Sales bPLN' = EXTERNALMEASURE("Net Sales bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bPLN
		lineageTag: cde87d63-0e67-496e-8523-1d357a7ebd76
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net Sales bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net Sales bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net Sales EUR' = EXTERNALMEASURE("Net Sales EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary holding EUR
		lineageTag: 6e1e44de-ef65-4613-bac3-04652fc5a95c
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net Sales EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net Sales EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net Sales bEUR' = EXTERNALMEASURE("Net Sales bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bEUR
		lineageTag: 741e8df8-dd5e-4247-9e67-fb5cfa1af012
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net Sales bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net Sales bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net Sales CUR' = EXTERNALMEASURE("Net Sales CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: fc1181a8-7bec-4eea-a1fa-b211a97729de
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net Sales CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net Sales CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net Sales CtrlPLN' = EXTERNALMEASURE("Net Sales CtrlPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary kontrolingowe CtrlPLN
		lineageTag: 118403bc-6995-4906-aa84-3c61ccc2c0e3
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net Sales CtrlPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net Sales CtrlPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Net Sales CUR Dom' = EXTERNALMEASURE("Net Sales CUR Dom", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: f5ecf96d-59a7-4a97-953d-fa6e55dd36b6
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Net Sales CUR Dom
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Net Sales CUR Dom FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Manufacturing Cost bPLN' = EXTERNALMEASURE("Manufacturing Cost bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bPLN
		lineageTag: a5af43bc-2c0d-48a7-8bb3-a5683650c519
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Manufacturing Cost bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Manufacturing Cost bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Manufacturing Cost EUR' = EXTERNALMEASURE("Manufacturing Cost EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary holding EUR
		lineageTag: 00560030-c38d-45ee-862b-6fdf2d1105c5
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Manufacturing Cost EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Manufacturing Cost EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Manufacturing Cost bEUR' = EXTERNALMEASURE("Manufacturing Cost bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bEUR
		lineageTag: 87150fca-740e-48ca-8772-7c20e656fcd8
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Manufacturing Cost bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Manufacturing Cost bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Manufacturing Cost CUR' = EXTERNALMEASURE("Manufacturing Cost CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: 3c1188ca-9f49-43c8-874e-650da79b2adf
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Manufacturing Cost CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Manufacturing Cost CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Manufacturing Cost CtrlPLN' = EXTERNALMEASURE("Manufacturing Cost CtrlPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary kontrolingowe CtrlPLN
		lineageTag: 0f91726f-3f45-47cf-a804-5b9432b01ec3
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Manufacturing Cost CtrlPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Manufacturing Cost CtrlPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Manufacturing Cost CUR Dom' = EXTERNALMEASURE("Manufacturing Cost CUR Dom", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary walutowe CUR
		lineageTag: cb10bbbb-5025-4750-9c91-58ae9d605aee
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Manufacturing Cost CUR Dom
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Manufacturing Cost CUR Dom FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'PLN Net Curr Rate' = EXTERNALMEASURE("PLN Net Curr Rate", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary wyliczane czasowe
		lineageTag: 1a281c03-118b-4424-87da-2f6da3415efd
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.PLN Net Curr Rate
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_PLN Net Curr Rate FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Group Margin CtrlPLN' = EXTERNALMEASURE("Group Margin CtrlPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary kontrolingowe CtrlPLN
		lineageTag: 64e944fa-d679-4853-a8d9-7461de479252
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Group Margin CtrlPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Group Margin CtrlPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'License Cost PLN' = EXTERNALMEASURE("License Cost PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Licencja koszt
		lineageTag: f88e70e2-061c-4f8c-8ccd-3553effd85fd
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.License Cost PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_License Cost PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Mnf Cost PLN Prev Year Price' = EXTERNALMEASURE("Mnf Cost PLN Prev Year Price", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Cena wytworzenia poprz rok
		lineageTag: 8d72155e-0f11-4922-bbf9-e5d1edb533e6
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Mnf Cost PLN Prev Year Price
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Mnf Cost PLN Prev Year Price FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Mnf Cost bPLN Prev Year Price' = EXTERNALMEASURE("Mnf Cost bPLN Prev Year Price", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary budżetowe bPLN
		lineageTag: 6168a280-dd88-4a16-95d7-7b2b998afa56
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Mnf Cost bPLN Prev Year Price
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Mnf Cost bPLN Prev Year Price FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Mnf Cost EUR Prev Year Price' = EXTERNALMEASURE("Mnf Cost EUR Prev Year Price", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Cena wytworzenia poprz rok
		lineageTag: 9778e057-1147-4092-94b8-1db29a99c22a
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Mnf Cost EUR Prev Year Price
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Mnf Cost EUR Prev Year Price FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Mnf Cost bEUR Prev Year Price' = EXTERNALMEASURE("Mnf Cost bEUR Prev Year Price", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Cena wytworzenia poprz rok
		lineageTag: 4f70a5dc-3f47-4341-ac72-e3dce6abe460
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Mnf Cost bEUR Prev Year Price
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Mnf Cost bEUR Prev Year Price FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Margin I PLN' = EXTERNALMEASURE("Margin I PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Measures
		lineageTag: e63a0580-dd08-4050-892e-7f0d48e15e40
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Margin I PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Margin I PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Margin I EUR' = EXTERNALMEASURE("Margin I EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Measures
		lineageTag: 68a9ca4b-1afd-4f8a-bf05-468b1c7654e6
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Margin I EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Margin I EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Margin I CUR' = EXTERNALMEASURE("Margin I CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Measures
		lineageTag: c7c73d90-1319-4017-bda9-4edd0e9d689f
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Margin I CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Margin I CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Margin I bPLN' = EXTERNALMEASURE("Margin I bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Measures
		lineageTag: d3ca1b6f-de26-4497-9c56-843e56d92d37
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Margin I bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Margin I bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Margin I bEUR' = EXTERNALMEASURE("Margin I bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Measures
		lineageTag: a7a6af6b-9074-49e6-9e0a-9c6b5ce119ab
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Margin I bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Margin I bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Margin I (%) PLN' = EXTERNALMEASURE("Margin I (%) PLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Measures
		lineageTag: bdc95559-7dcc-419e-b70c-bc5882ad254a
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Margin I (%) PLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Margin I (%) PLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Margin I (%) EUR' = EXTERNALMEASURE("Margin I (%) EUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Measures
		lineageTag: 4584d5e4-ab00-4a50-9251-c0d3ebb62942
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Margin I (%) EUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Margin I (%) EUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Margin I (%) CUR' = EXTERNALMEASURE("Margin I (%) CUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Measures
		lineageTag: ad8b29ff-e564-4c7f-be2f-633096569bb9
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Margin I (%) CUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Margin I (%) CUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Margin I (%) bPLN' = EXTERNALMEASURE("Margin I (%) bPLN", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Measures
		lineageTag: 05eb935d-7be9-4811-9386-cca9766c8fd4
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Margin I (%) bPLN
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Margin I (%) bPLN FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Margin I (%) bEUR' = EXTERNALMEASURE("Margin I (%) bEUR", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Measures
		lineageTag: 436688ba-86e3-450b-bcc3-73b4f137bac0
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Margin I (%) bEUR
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Margin I (%) bEUR FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Number of Orders' = EXTERNALMEASURE("Number of Orders", INTEGER, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Measures
		lineageTag: ebb37983-1fd1-4022-8901-648af082c931
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Number of Orders
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Number of Orders FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	measure 'Current Manufacturing Cost' = EXTERNALMEASURE("Current Manufacturing Cost", DOUBLE, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")
		displayFolder: Miary
		lineageTag: 3e002c7f-87c8-4502-8cd0-19c23333777b
		sourceLineageTag: Połączenie DirectQuery z elementem AS — Sales Tabular Model.Current Manufacturing Cost
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Current Manufacturing Cost FormatString", STRING, "Połączenie DirectQuery z elementem AS — Sales Tabular Model")

	column prod_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 349e1df2-8e8d-444c-9050-0e4a9a8f3183
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: prod_id

		annotation SummarizationSetBy = User

	column prod_inv_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 8003cb78-f0cb-4bff-b4a2-9ce4182460a5
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: prod_inv_id

		annotation SummarizationSetBy = User

	column cat_type_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 3d51b03e-aefa-41a3-b7c7-4a3e721c67e6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: cat_type_id

		annotation SummarizationSetBy = User

	column invoice_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: b98c8e5d-ee8a-4bf9-846e-9b46dbf59603
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: invoice_id

		annotation SummarizationSetBy = User

	column curr_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 7f95e4eb-ca27-4024-a76b-e39eca50df54
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: curr_id

		annotation SummarizationSetBy = User

	column curr_dom_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: dc42ee89-ac88-456e-8407-8adbed6c6bc7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: curr_dom_id

		annotation SummarizationSetBy = User

	column org_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 6586ea3d-2a02-4a10-94bd-d2a8c0c7785e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: org_id

		annotation SummarizationSetBy = User

	column dest_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 8a223087-b715-4adf-aa75-a6ab317844cb
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: dest_id

		annotation SummarizationSetBy = User

	column cust_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 05784c3a-af7c-4e4a-8122-ec3de8c4ae44
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: cust_id

		annotation SummarizationSetBy = User

	column comp_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 2e4aa1fe-dba8-43fe-8aaa-10f9f92580b9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: comp_id

		annotation SummarizationSetBy = User

	column var_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 42a718d8-d965-4120-809f-690b74177d4a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: var_id

		annotation SummarizationSetBy = User

	column sman_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 798fac1d-22c5-4756-a856-4b1eea7bff25
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: sman_id

		annotation SummarizationSetBy = User

	column cord_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: c0a2f301-ebbe-40b3-8605-4bb112544f44
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: cord_id

		annotation SummarizationSetBy = User

	column mseg_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 4fcba39c-69ab-4fbd-81e6-74f4d73a3e9c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: mseg_id

		annotation SummarizationSetBy = User

	column account_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 3a1a7872-d9bc-4bad-b0ec-77ed30c52179
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: account_id

		annotation SummarizationSetBy = User

	column c_grp_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 2aecb6f1-541d-4ce5-b0d1-60dd56186ebd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: c_grp_id

		annotation SummarizationSetBy = User

	column c_reg_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 526faf2a-c6e1-431b-94c2-4fa3fea42ec2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: c_reg_id

		annotation SummarizationSetBy = User

	column c_country_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: e75319ce-040b-45de-94f0-c3f5922f203e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: c_country_id

		annotation SummarizationSetBy = User

	column c_area_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 1aed7bad-7d0a-4d1a-bb57-7b6b7b3359f8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: c_area_id

		annotation SummarizationSetBy = User

	column s_sta_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: c5f50faf-749f-4d1c-93ab-9d5fcef2157b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: s_sta_id

		annotation SummarizationSetBy = User

	column d_term_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 185cadae-3b8b-4996-a536-b0d716cc63de
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: d_term_id

		annotation SummarizationSetBy = User

	column ord_rec_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: aabca7d1-b5b0-42a7-939c-e89c4fc19d1d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ord_rec_id

		annotation SummarizationSetBy = User

	column skonto_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: a0b6edc3-0717-4398-8f53-3689bd64eb3c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: skonto_id

		annotation SummarizationSetBy = User

	column prj_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 926f5661-78a0-41cc-a4ae-149459a564e8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: prj_id

		annotation SummarizationSetBy = User

	column invent_um_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 2b98b373-534a-49dd-a580-1dc15211e997
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: invent_um_id

		annotation SummarizationSetBy = User

	column sale_um_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 8e5736bc-d4f8-4405-89bb-a140a53d697b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: sale_um_id

		annotation SummarizationSetBy = User

	column price_um_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: dc32d8f2-fdb3-4d9f-a8bb-99da35db2132
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: price_um_id

		annotation SummarizationSetBy = User

	column lic_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 515db3c5-956d-4c69-8efc-6576992f85a1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: lic_id

		annotation SummarizationSetBy = User

	column s_pln_gcost
		dataType: double
		isHidden
		lineageTag: e12b78af-0a5e-49a9-afc3-6a9a1a14d1e1
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_pln_gcost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_pln_lic_cost_ns
		dataType: double
		isHidden
		lineageTag: cdf8412a-43f6-45ff-b0e0-60ce990cfe6a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_pln_lic_cost_ns

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_bpln_lic_cost
		dataType: double
		isHidden
		lineageTag: a5179f4f-30c5-4208-8010-f3f095371b82
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_bpln_lic_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_bpln_lic_cost_ns
		dataType: double
		isHidden
		lineageTag: bc331100-0cd8-49a8-9b7d-9b870536cd55
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_bpln_lic_cost_ns

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_eur_gcost
		dataType: double
		isHidden
		lineageTag: 2a61823c-411d-4fe9-8f76-d0fc13af2bfa
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_eur_gcost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_eur_lic_cost
		dataType: double
		isHidden
		lineageTag: 21a4296d-57c8-48f3-8ff1-fce03a8d22fe
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_eur_lic_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_eur_lic_cost_ns
		dataType: double
		isHidden
		lineageTag: cefed0f3-f862-4ae0-aa03-7a1ef224b35a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_eur_lic_cost_ns

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_beur_lic_cost
		dataType: double
		isHidden
		lineageTag: 5c646d67-01a8-4365-9f80-b4b8c89f0db1
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_beur_lic_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_beur_lic_cost_ns
		dataType: double
		isHidden
		lineageTag: c6147b47-271a-4aaa-9323-879f0e9704a2
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_beur_lic_cost_ns

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_cur_lic_cost
		dataType: double
		isHidden
		lineageTag: d38de105-b49f-4eb9-bd64-7bb4619afa37
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_cur_lic_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_cur_lic_cost_ns
		dataType: double
		isHidden
		lineageTag: a03d3dd5-cfce-4ee1-a13d-f6da0b656a3f
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_cur_lic_cost_ns

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_dom_bcost
		dataType: double
		isHidden
		lineageTag: 5bbbb3fa-7335-4913-b9ba-badb22db9898
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_dom_bcost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_gbp_net
		dataType: double
		isHidden
		lineageTag: 4b523a84-6a23-4d65-b7a2-f6f76a4a410b
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_gbp_net

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column s_bgbp_net
		dataType: double
		isHidden
		lineageTag: ac252be3-c35e-4307-95d7-09a4ba433aff
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_bgbp_net

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column m_pln_group
		dataType: double
		isHidden
		lineageTag: a9a1cba5-64bf-45c9-bbe1-4ba93ca540a6
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: m_pln_group

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column m_bpln_group
		dataType: double
		isHidden
		lineageTag: db56bca0-66f1-46ee-8448-cf6c9ba8a3d0
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: m_bpln_group

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column m_eur_group
		dataType: double
		isHidden
		lineageTag: 6db541e5-393d-4e03-821c-8bc7e1fbd035
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: m_eur_group

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column m_beur_group
		dataType: double
		isHidden
		lineageTag: f67036fe-271e-4077-9dbe-4300f2bd9a37
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: m_beur_group

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column m_cur_group
		dataType: double
		isHidden
		lineageTag: 3aa2ebb8-9b9b-48cf-8101-bceab24b4797
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: m_cur_group

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Internal sales'
		dataType: string
		displayFolder: Miary transakcyjne
		lineageTag: df028673-6025-4063-8a9f-66e330c9fcd8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Internal sales

		annotation SummarizationSetBy = Automatic

	column 'Order number'
		dataType: string
		displayFolder: Miary transakcyjne
		lineageTag: f8b35b11-20f6-4101-a82c-d209e7d3ac55
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Order number

		annotation SummarizationSetBy = Automatic

	column Contract
		dataType: string
		displayFolder: Miary transakcyjne
		lineageTag: 7914bd01-bd35-451d-b4b0-2e847c5f8c80
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Contract

		annotation SummarizationSetBy = Automatic

	column src_supply_code
		dataType: string
		displayFolder: Transaction Measures
		lineageTag: 8c965c80-b692-4089-b92a-1f7e1cdf521a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: src_supply_code

		annotation SummarizationSetBy = Automatic

	column 'Lot Batch No'
		dataType: string
		displayFolder: Miary transakcyjne
		lineageTag: 1d9ad5e1-ce00-40a8-8422-2c3afa33c261
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Lot Batch No

		annotation SummarizationSetBy = Automatic

	column 'Customer Order No'
		dataType: string
		displayFolder: Miary transakcyjne
		lineageTag: b2d5fc7a-0f75-40c5-9826-0f3dd82df2b3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Customer Order No

		annotation SummarizationSetBy = Automatic

	column 'Crossdock Address Id'
		dataType: string
		displayFolder: Miary transakcyjne
		lineageTag: 742c6c32-3720-4959-8e97-16c158fde353
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Crossdock Address Id

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		displayFolder: Miary transakcyjne
		lineageTag: 16a20b53-37c2-4d36-a798-94f0328aee93
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column 'BI Sales'
		dataType: int64
		formatString: 0
		displayFolder: Miary transakcyjne
		lineageTag: 44a3ab87-f8d0-4b27-bf57-429fd396d118
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: BI Sales

		annotation SummarizationSetBy = User

	column time_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: dacabc73-8034-4832-9575-0019f55f6722
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: time_id

		annotation SummarizationSetBy = User

	column 'Invoice number'
		dataType: string
		displayFolder: Miary transakcyjne
		lineageTag: 8fda4267-5a16-4015-b623-c5e385144cdc
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Invoice number

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		displayFolder: Miary transakcyjne
		lineageTag: ce32194e-72fb-49d0-b902-b78ef297d625
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column supp_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: d13be3f2-f147-4b86-a3d2-41cd0958a8c5
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: supp_id

		annotation SummarizationSetBy = User

	column pricelist_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 0734a0f0-c934-4549-8722-1aca35b69c8b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: pricelist_id

		annotation SummarizationSetBy = User

	column ord_supp_type_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: 02ac7701-42aa-4a02-b0df-ac5168591173
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ord_supp_type_id

		annotation SummarizationSetBy = User

	column 'Order Reference Code'
		dataType: string
		displayFolder: Miary transakcyjne
		lineageTag: b2a3d2bb-b88e-416b-b95d-d1b077c39cfa
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Order Reference Code

		annotation SummarizationSetBy = Automatic

	column sale_qty
		dataType: double
		isHidden
		formatString: 0.0000
		displayFolder: Measures
		lineageTag: b28caac2-30d5-4430-a696-a60dea855931
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: sale_qty

		annotation SummarizationSetBy = User

	column s_pln_cat
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Measures
		lineageTag: 754745df-8074-4452-9aeb-f75f979cad4a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_pln_cat

		annotation SummarizationSetBy = User

	column s_pln_ofe
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Measures
		lineageTag: 53c235ed-90cb-4e1a-b3a8-4be0f774955d
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_pln_ofe

		annotation SummarizationSetBy = User

	column s_pln_base
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Measures
		lineageTag: f6ac93df-2fca-4c8e-86f1-c362d124eecc
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_pln_base

		annotation SummarizationSetBy = User

	column s_pln_net
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Measures
		lineageTag: aef94c79-18f0-4d89-8b5c-b9fbabb34507
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_pln_net

		annotation SummarizationSetBy = User

	column s_pln_cost
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Measures
		lineageTag: 6661aa2c-5de3-48f1-b522-2c448d7141a2
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_pln_cost

		annotation SummarizationSetBy = User

	column s_pln_bcost
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Measures
		lineageTag: 9a77080d-cf59-4509-b3c0-345a0ff389fa
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_pln_bcost

		annotation SummarizationSetBy = User

	column s_pln_corp_cost
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Measures
		lineageTag: 219494b3-f03c-4bee-91ba-b12eeff9021a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_pln_corp_cost

		annotation SummarizationSetBy = User

	column s_pln_corp_cost_ya
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Previous Year Mnf Price
		lineageTag: 3964eaff-3445-4d59-9f81-4ff59eb6fa3a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_pln_corp_cost_ya

		annotation SummarizationSetBy = User

	column s_pln_lic_cost
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: License Cost
		lineageTag: 7aa327ef-6f51-473b-ae02-5f00517ab868
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_pln_lic_cost

		annotation SummarizationSetBy = User

	column kwdr_pln
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Measures
		lineageTag: 09ac0bd5-1eaa-4404-a61c-6d5c9855ade4
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: kwdr_pln

		annotation SummarizationSetBy = User

	column s_bpln_cat
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Budget Measures bPLN
		lineageTag: b427dee5-a3b0-4190-83e5-7e7b284a1da0
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_bpln_cat

		annotation SummarizationSetBy = User

	column s_bpln_ofe
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Budget Measures bPLN
		lineageTag: b08b6bba-a3c1-4eae-a1e2-3d8836a85a95
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_bpln_ofe

		annotation SummarizationSetBy = User

	column s_bpln_base
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Budget Measures bPLN
		lineageTag: 9c973ab0-1ee7-4d23-8d95-d6ca93e738d5
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_bpln_base

		annotation SummarizationSetBy = User

	column s_bpln_net
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Budget Measures bPLN
		lineageTag: ba54744d-02b9-4b0d-858f-d9519cb49024
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_bpln_net

		annotation SummarizationSetBy = Automatic

	column s_bpln_cost
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Budget Measures bPLN
		lineageTag: 096b0501-d460-40cd-a70b-6ae01476d1d0
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_bpln_cost

		annotation SummarizationSetBy = User

	column s_bpln_bcost
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Budget Measures bPLN
		lineageTag: 41f18431-683f-4a9c-bae4-5685da8736e0
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_bpln_bcost

		annotation SummarizationSetBy = User

	column s_bpln_corp_cost
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Budget Measures bPLN
		lineageTag: 7d4419b5-5445-4712-aca6-a05326bd6f96
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_bpln_corp_cost

		annotation SummarizationSetBy = User

	column s_bpln_corp_cost_ya
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Previous Year Mnf Price
		lineageTag: e23e3759-e454-4e84-8f7b-ec7d69f5cc60
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_bpln_corp_cost_ya

		annotation SummarizationSetBy = User

	column s_eur_cat
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Holding Measures EUR
		lineageTag: 1e059ba8-8cfc-4f4d-bc48-8b9409ee095f
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_eur_cat

		annotation SummarizationSetBy = User

	column s_eur_ofe
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Holding Measures EUR
		lineageTag: 1d4beb81-e26b-4d87-a60e-79779fe30cf0
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_eur_ofe

		annotation SummarizationSetBy = User

	column s_eur_base
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Holding Measures EUR
		lineageTag: 7d68f3a9-bda3-436c-b632-46ae6413aed4
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_eur_base

		annotation SummarizationSetBy = User

	column s_eur_net
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Holding Measures EUR
		lineageTag: 2f6e9606-16ed-4076-9ef3-b8b1e9a144d1
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_eur_net

		annotation SummarizationSetBy = User

	column s_eur_cost
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Holding Measures EUR
		lineageTag: a42e88f9-f602-4218-aafb-0a5f7df5191c
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_eur_cost

		annotation SummarizationSetBy = User

	column s_eur_bcost
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Holding Measures EUR
		lineageTag: 8cd73ffb-6846-4b49-b330-2c6661dea7e6
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_eur_bcost

		annotation SummarizationSetBy = User

	column s_eur_corp_cost
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Holding Measures EUR
		lineageTag: 80eacf11-40b8-4932-9dbd-a88b385a653a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_eur_corp_cost

		annotation SummarizationSetBy = User

	column s_eur_corp_cost_ya
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Previous Year Mnf Price
		lineageTag: 9be927e2-9da9-4195-a7c6-582ff1188b8a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_eur_corp_cost_ya

		annotation SummarizationSetBy = User

	column s_beur_cat
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Budget Measures bEUR
		lineageTag: 145be1a8-de55-4c54-938f-1ef92bb94626
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_beur_cat

		annotation SummarizationSetBy = User

	column s_beur_ofe
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Budget Measures bEUR
		lineageTag: 681b10cc-cf37-46b3-8f42-918ebce62c35
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_beur_ofe

		annotation SummarizationSetBy = User

	column s_beur_base
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Budget Measures bEUR
		lineageTag: 2302cf0b-94b5-4cac-a04e-ac7055d7584d
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_beur_base

		annotation SummarizationSetBy = User

	column s_beur_net
		dataType: double
		isHidden
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: Budget Measures bEUR
		lineageTag: 9c5de3f0-55fe-4add-bfdd-0e4850d6e534
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_beur_net

		annotation SummarizationSetBy = User

	column s_beur_cost
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Budget Measures bEUR
		lineageTag: 76e2dfea-1b73-4cc6-866a-6bcdfbeefac9
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_beur_cost

		annotation SummarizationSetBy = User

	column s_beur_bcost
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Budget Measures bEUR
		lineageTag: ce4e13cc-ceb4-4e6a-bfc8-1c24a3ae2f23
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_beur_bcost

		annotation SummarizationSetBy = User

	column s_beur_corp_cost
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Budget Measures bEUR
		lineageTag: 16f0c895-9332-48a0-8ef6-194b4b819895
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_beur_corp_cost

		annotation SummarizationSetBy = User

	column s_beur_corp_cost_ya
		dataType: double
		isHidden
		formatString: "€" \#\,\0.\0\0\;-"€" \#\,\0.\0\0\;"€" \#\,\0.\0\0
		displayFolder: Previous Year Mnf Price
		lineageTag: 7ed24d9f-9218-4006-a827-bec09b527390
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_beur_corp_cost_ya

		annotation SummarizationSetBy = User

	column s_cur_cat
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Currency measures CUR
		lineageTag: 1e385693-1e4d-48a5-b7b2-9a9a6a862098
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_cur_cat

		annotation SummarizationSetBy = User

	column s_cur_ofe
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Currency measures CUR
		lineageTag: b813837a-819e-48fa-9117-05e81fbfaf38
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_cur_ofe

		annotation SummarizationSetBy = User

	column s_cur_base
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Currency measures CUR
		lineageTag: b9997261-121f-4fcb-acae-8eafafd31f1f
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_cur_base

		annotation SummarizationSetBy = User

	column s_cur_net
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Currency measures CUR
		lineageTag: 3dfe4a02-352a-4d79-84f7-ec588fba2a55
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_cur_net

		annotation SummarizationSetBy = User

	column s_cur_cost
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Currency measures CUR
		lineageTag: 11884904-2414-42b7-b2fa-a626be504971
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_cur_cost

		annotation SummarizationSetBy = User

	column s_cur_bcost
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Currency measures CUR
		lineageTag: 0ca20cdb-7e28-4244-8610-6df600268932
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_cur_bcost

		annotation SummarizationSetBy = User

	column s_cur_corp_cost
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Currency measures CUR
		lineageTag: f26eebaf-c118-43b1-bce5-d6db5539ede7
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_cur_corp_cost

		annotation SummarizationSetBy = User

	column s_ctrlpln_net
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Controlling Measures CtrlPLN
		lineageTag: 9b0711ff-1416-43d1-8586-9c21bfda3fd0
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_ctrlpln_net

		annotation SummarizationSetBy = User

	column s_ctrlpln_cat
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Controlling Measures CtrlPLN
		lineageTag: 3c96e25c-77ce-4b9e-980e-a5adb6a7b63d
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_ctrlpln_cat

		annotation SummarizationSetBy = User

	column s_ctrlpln_ofe
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Controlling Measures CtrlPLN
		lineageTag: d4c02c35-4994-4c67-815d-776affb4b8f7
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_ctrlpln_ofe

		annotation SummarizationSetBy = User

	column s_ctrlpln_base
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Controlling Measures CtrlPLN
		lineageTag: 693fff34-4920-4cba-9b12-bc5e10446801
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_ctrlpln_base

		annotation SummarizationSetBy = User

	column s_ctrlpln_cost
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Controlling Measures CtrlPLN
		lineageTag: e771c70b-706e-4052-923a-3f09e0969acd
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_ctrlpln_cost

		annotation SummarizationSetBy = User

	column s_ctrlpln_bcost
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Controlling Measures CtrlPLN
		lineageTag: ee84b192-7aa5-4ede-bd26-5603ebe83bda
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_ctrlpln_bcost

		annotation SummarizationSetBy = User

	column s_ctrlpln_corp_cost
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Controlling Measures CtrlPLN
		lineageTag: 2de12c0a-4aba-4094-a4cc-a5c7638be08a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_ctrlpln_corp_cost

		annotation SummarizationSetBy = User

	column s_dom_net
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Currency measures CUR
		lineageTag: fee90f30-8a0f-4ae5-a5df-b77466e30e4a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_dom_net

		annotation SummarizationSetBy = User

	column s_dom_cost
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Currency measures CUR
		lineageTag: 927e6558-6087-4832-a8ac-be07360e0511
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_dom_cost

		annotation SummarizationSetBy = User

	column s_dom_corp_cost
		dataType: double
		isHidden
		formatString: #,0.00\ "";-#,0.00\ "";#,0.00\ ""
		displayFolder: Currency measures CUR
		lineageTag: a72a7680-760b-48da-aa3a-df39d82a9279
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_dom_corp_cost

		annotation SummarizationSetBy = User

	column s_pln_net_cur_rate
		dataType: double
		isHidden
		formatString: 0.00
		displayFolder: Calculated measures time
		lineageTag: af01b8de-8607-4afe-acbf-cd4bd60768ce
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: s_pln_net_cur_rate

		annotation SummarizationSetBy = User

	column m_ctrlpln_group
		dataType: double
		isHidden
		formatString: #,0.00\ "zł";-#,0.00\ "zł";#,0.00\ "zł"
		displayFolder: Controlling Measures CtrlPLN
		lineageTag: eb70fcaf-9155-42b5-a831-41bbc77eac26
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: m_ctrlpln_group

		annotation SummarizationSetBy = User

	column invent_qty
		dataType: double
		isHidden
		formatString: 0.0000
		displayFolder: Measures
		lineageTag: 4d7e5e62-c4d9-4ee0-beb0-a526320c300e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: invent_qty

		annotation SummarizationSetBy = User

	column dest_ord_id
		dataType: int64
		isHidden
		isNullable: false
		formatString: 0
		lineageTag: f081afe6-c9b3-42a3-9d50-101472f92be5
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: dest_ord_id

		annotation SummarizationSetBy = User

	column team_id
		dataType: int64
		isNullable: false
		formatString: 0
		displayFolder: Transaction Measures
		lineageTag: d4658bb5-5a70-4b50-bb6a-d882d2124b26
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: team_id

		annotation SummarizationSetBy = User

	partition 'Sales Measures' = entity
		mode: directQuery
		source
			entityName: Sales Measures
			expressionSource: 'Połączenie DirectQuery z elementem AS — Sales Tabular Model'

