table _Miary_Data
	lineageTag: 49420611-2b42-4d2b-8f5c-27ca3e52f71c

	measure 'DATA MON c_eur_assembly' = SUM(f_margin_mon_data[c_eur_assembly])
		displayFolder: DATA MON
		lineageTag: c36fa8b2-78a2-446d-890e-61f00677d856

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_eur_comm' = SUM(f_margin_mon_data[c_eur_comm])
		displayFolder: DATA MON
		lineageTag: 00cf3d76-e170-4fac-87c2-7b8b8555f4f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_eur_compl_act' = SUM(f_margin_mon_data[c_eur_compl_act])
		displayFolder: DATA MON
		lineageTag: 6bbe675f-3e05-49cf-b266-e5154ee0bebd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_eur_compl_prod' = SUM(f_margin_mon_data[c_eur_compl_prod])
		displayFolder: DATA MON
		lineageTag: 12c6b133-6b92-4010-a176-12386b7198da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_eur_lic' = SUM(f_margin_mon_data[c_eur_lic])
		displayFolder: DATA MON
		lineageTag: f81eb386-979e-4929-8f7d-ab2bd94edaf7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_eur_sinsuran' = SUM(f_margin_mon_data[c_eur_sinsuran])
		displayFolder: DATA MON
		lineageTag: a2a7037b-d610-44b6-8281-366752f7e6a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_eur_stock_deprec' = SUM(f_margin_mon_data[c_eur_stock_deprec])
		displayFolder: DATA MON
		lineageTag: 31d93149-8bd3-43e0-8d4c-93434f67760d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_eur_transport' = SUM(f_margin_mon_data[c_eur_transport])
		displayFolder: DATA MON
		lineageTag: 00a4d48d-791c-4179-9351-297d2bc13758

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_eur_varfixed' = SUM(f_margin_mon_data[c_eur_varfixed])
		displayFolder: DATA MON
		lineageTag: ed94815b-b051-4f7d-a175-7544b672ec46

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_pln_assembly' = SUM(f_margin_mon_data[c_pln_assembly])
		displayFolder: DATA MON
		lineageTag: c3f47873-ffd7-4f03-8cb0-1e573ff49147

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_pln_comm' = SUM(f_margin_mon_data[c_pln_comm])
		displayFolder: DATA MON
		lineageTag: 8771a304-36c7-472a-aea6-7b9c45416bf5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_pln_compl_act' = SUM(f_margin_mon_data[c_pln_compl_act])
		displayFolder: DATA MON
		lineageTag: 3036e4ad-8789-43c9-aaea-0b28e7ec1aa1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_pln_compl_prod' = SUM(f_margin_mon_data[c_pln_compl_prod])
		displayFolder: DATA MON
		lineageTag: 76c8d763-3834-4031-8623-834878bebb7b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_pln_lic' = SUM(f_margin_mon_data[c_pln_assembly])
		displayFolder: DATA MON
		lineageTag: e109d59a-fcff-4b83-adbd-34e87bde2040

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_pln_sinsuran' = SUM(f_margin_mon_data[c_pln_sinsuran])
		displayFolder: DATA MON
		lineageTag: 1bbefaec-4381-40a1-bf49-a4f594db1796

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_pln_stock_deprec' = SUM(f_margin_mon_data[c_pln_stock_deprec])
		displayFolder: DATA MON
		lineageTag: 4929b05b-f84f-4e20-8024-4eec46d32910

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_pln_transport' = SUM(f_margin_mon_data[c_pln_transport])
		displayFolder: DATA MON
		lineageTag: 647aca09-cce5-4b43-b696-f2fbdd5ae0b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON c_pln_varfixed' = SUM(f_margin_mon_data[c_pln_varfixed])
		displayFolder: DATA MON
		lineageTag: 378264bb-a33f-4226-8d17-31eb65b63c10

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON s_eur_corp_cost' = SUM(f_margin_mon_data[s_eur_corp_cost])
		displayFolder: DATA MON
		lineageTag: cbc45486-f9b0-40fd-8df9-b4f92e7e54df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DATA MON s_pln_corp_cost' = SUM(f_margin_mon_data[s_pln_corp_cost])
		displayFolder: DATA MON
		lineageTag: 88628e3d-191c-4d3c-b0e1-16ed8ae0ec0c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		formatString: 0
		lineageTag: c0f453e4-9b46-48af-8ef8-2495b4383a58
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Miary_Data = calculated
		mode: import
		source = {0}

	annotation PBI_Id = a2b0fdddd39a4e41842a285ade1d829d

