table 'Empl Type'
	lineageTag: 86ce385c-0d0f-4aa7-a3ac-a30b0c530568

	column empl_type_id
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 713b83e0-4b2f-43d5-8cbe-47c794936d6c
		summarizeBy: none
		sourceColumn: empl_type_id

		annotation SummarizationSetBy = Automatic

	column 'Empl Type Code'
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: bf33d0b6-d233-481b-a756-15a43d95b1c6
		summarizeBy: none
		sourceColumn: Empl Type Code

		annotation SummarizationSetBy = Automatic

	column empl_type_name
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 357d6fb3-8ec5-4762-a510-e1579f16f25d
		summarizeBy: none
		sourceColumn: empl_type_name

		annotation SummarizationSetBy = Automatic

	partition 'Empl Type' = m
		mode: directQuery
		source =
				let
				    Source = Databricks.Catalogs("adb-16306551450739.19.azuredatabricks.net", "/sql/1.0/warehouses/58af2438595b0abd", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null, Protocol=null]),
				    prd_Database = Source{[Name="prd",Kind="Database"]}[Data],
				    solet_Schema = prd_Database{[Name="solet",Kind="Schema"]}[Data],
				    d_salary_cost_empl_type_Table = solet_Schema{[Name="d_salary_cost_empl_type",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(d_salary_cost_empl_type_Table,{{"empl_type_code", "Empl Type Code"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

