table _Miary
	lineageTag: fce809bd-c1a1-4265-b842-278345ddfbe1

	measure Wydatki =
			
			ROUND(
			    SUM(f_capex_imp_cost_data[amount_pln]),
			    0
			)
		formatString: #,0.00
		lineageTag: 295b12e5-d9a0-457b-a5b2-7fcb9103c641

	measure 'Nazwa projektu - tytul' =
			
			IF( NOT ISFILTERED(vm_pbi_d_gl_project[prj_desc]),
			    "Budżet wdrożeń",
			    IF( HASONEVALUE(vm_pbi_d_gl_project[prj_desc]),
			        VALUES(vm_pbi_d_gl_project[prj_desc]),
			        "Kilka projektów" )
			)
		lineageTag: b6e08fcd-fedb-45b4-bb85-c74858294be6

	measure 'Ilość otwartych projektów' =
			
			COUNTROWS (
			    DISTINCT(
			        FILTER(
			            VALUES('vm_pbi_d_gl_project'[prj_desc]),
			            LEFT ('vm_pbi_d_gl_project'[prj_desc], 3) <> "(X)"
			        )
			    )
			)
		formatString: 0
		lineageTag: d8358878-8d59-40fd-a985-73ad8eae745c

	measure 'Ilosc otwartych projektow wg statusow' =
			
			
			COUNTROWS(
			    DISTINCT(
			    FILTER(
			        vm_pbi_d_gl_project,
			        vm_pbi_d_gl_project[status] = "Aktywny"
			    )
			)
			)
		formatString: 0
		lineageTag: ff3f4611-a439-44b2-a121-51817b979cd1

	measure 'Numer projektu - tytul' =
			
			IF( NOT ISFILTERED(vm_pbi_d_gl_project[prj_desc]),
			    "Wybierz projekt",
			    IF( HASONEVALUE(vm_pbi_d_gl_project[hprj_code]),
			        VALUES(vm_pbi_d_gl_project[hprj_code]),
			        "Kilka projektów")
			)
		lineageTag: 0490d09a-711e-4302-9875-25436384c6c6

	measure 'Budzet projektu' = ```
			
			
			SUM(vm_pbi_d_projects_budget[debet_amount])
			
			```
		formatString: #,0.00
		lineageTag: 467e429d-ecbc-48a8-8151-48417635da7e

	measure 'Realizacja budzetu %' = ```
			
			VAR Budzet_projektu = 
			    SUM(vm_pbi_d_projects_budget[debet_amount])
			
			VAR Wydatki = 
			    SUM(f_capex_imp_cost_data[amount_pln])
			
			RETURN
			
			DIVIDE(
			    [Wydatki],
			    [Budzet projektu],
			    ""
			 )
			
			```
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 0a1ed71e-7a2c-4f4e-928f-e3600efa60d1

	measure 'Widocznosc grafiki' = ```
			
			IF(
			    HASONEVALUE(vm_pbi_d_gl_project[prj_desc]),
			    "RGBA(255,0,0,0)",         
			    "RGBA(255,255,255,1)"
			)
			
			```
		lineageTag: 27778e1b-8db4-4dbc-b119-6f3b7b46de78

	measure Sprzedaz =
			
			SUM(vm_pbi_d_gl_project[s_pln_net_from_sales])
		formatString: #,0.00
		lineageTag: 075e393b-857f-4dff-917e-27c42297f1aa

	measure Marza_II =
			
			SUM(vm_pbi_d_gl_project[m_pln_margin_ii_from_margin])
		lineageTag: ab0c2d8a-18bb-4ee4-b9c3-65211b64a8d2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Zysk z wdrozenia' =
			
			[Marza_II]-[Wydatki]
			--oblicza zysk z wdrożenia biorąc pod uwagę tylko wygenerowaną marżę po 2024 bazują na modelu marży
		lineageTag: bfb82d26-b167-48a0-9de0-52b3302af165

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Marza_II_% = ```
			
			VAR margin_ii_net = 
			    sum(vm_pbi_d_gl_project[m_pln_margin_ii_from_margin])
			
			VAR sales = 
			    SUM(vm_pbi_d_gl_project[s_pln_net_from_margin])
			
			RETURN
			
			DIVIDE(
			    margin_ii_net,
			    sales,
			    "brak sprzedaży"
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 76eb7427-cb99-490f-81e7-9c51441295fa

	measure 'Ilosc miesiecy od pierwszej sprzedazy' =
			
			VAR DZIS = TODAY()
			VAR PIWERWSZA_SPRZEDAZ = MIN(vm_pbi_d_gl_project[first_sales])
			RETURN
			DATEDIFF(PIWERWSZA_SPRZEDAZ, DZIS, MONTH)
		formatString: 0
		lineageTag: ca24e34b-83da-4184-9856-4b7327457ccb

	measure 'Zwrot wdrozenia' =
			
			DIVIDE(
			    [Marza_II],
			    [Wydatki],
			    "BŁĄD"
			)
		formatString: 0%;-0%;0%
		lineageTag: 35a07a38-dbbf-468c-8c30-4d470148f7af

	measure username = USERNAME()
		lineageTag: 8d7b564f-c76d-4a2b-a203-9d1c13915671

	measure userprincipalname = USERPRINCIPALNAME()
		lineageTag: 69f07fed-d54e-480b-b910-d1b267c33cf2

	measure 'Wydatki - A-WDR-01' =
			
			ROUND(
			    CALCULATE(
			        SUM(f_capex_imp_cost_data[amount_pln]),
			        d_impl_cat_cost[impl_cat_cost_code] = "A-WDR-01"
			    ),
			    0
			)
		formatString: #,0
		lineageTag: c032c9d9-fe78-4f4c-80bc-95f2ab299378

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Wydatki - A-WDR-02' =
			
			ROUND(
			    CALCULATE(
			        SUM(f_capex_imp_cost_data[amount_pln]),
			        d_impl_cat_cost[impl_cat_cost_code] = "A-WDR-02"
			    ),
			    0
			)
		formatString: #,0
		lineageTag: a3835af6-076b-46b2-afc5-b295096a961d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Wydatki - A-WDR-03' =
			
			ROUND(
			    CALCULATE(
			        SUM(f_capex_imp_cost_data[amount_pln]),
			        d_impl_cat_cost[impl_cat_cost_code] = "A-WDR-03"
			    ),
			    0
			)
		formatString: #,0
		lineageTag: 456b8924-198f-4a24-bd03-3c744fb7c4e2

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Wydatki - A-WDR-04' =
			
			ROUND(
			    CALCULATE(
			        SUM(f_capex_imp_cost_data[amount_pln]),
			        d_impl_cat_cost[impl_cat_cost_code] = "A-WDR-04"
			    ),
			    0
			)
		formatString: #,0
		lineageTag: f2c1989f-e56f-4e22-8e54-747f97d7a07d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Wydatki - A-WDR-05' =
			
			ROUND(
			    CALCULATE(
			        SUM(f_capex_imp_cost_data[amount_pln]),
			        d_impl_cat_cost[impl_cat_cost_code] = "A-WDR-05"
			    ),
			    0
			)
		formatString: #,0
		lineageTag: 3b16b795-5da8-4082-9773-9017b164d6be

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Wydatki - A-WDR-06' =
			
			ROUND(
			    CALCULATE(
			        SUM(f_capex_imp_cost_data[amount_pln]),
			        d_impl_cat_cost[impl_cat_cost_code] = "A-WDR-06"
			    ),
			    0
			)
		formatString: #,0
		lineageTag: 29b1049e-d75f-4abd-97ef-041386a02a09

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Wydatki - A-WDR-07' =
			
			ROUND(
			    CALCULATE(
			        SUM(f_capex_imp_cost_data[amount_pln]),
			        d_impl_cat_cost[impl_cat_cost_code] = "A-WDR-07"
			    ),
			    0
			)
		formatString: #,0
		lineageTag: f11f0a4a-7679-4f7d-9274-b6a1d3f45ca8

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Budget Type' =
			
			SELECTEDVALUE(
			    vm_pbi_d_projects_budget[budget_type]
			)
		lineageTag: 89d7cbf1-1c09-4631-92ae-968831b2acbd

	measure 'Wydatki - A-WDR-99' =
			
			ROUND(
			    CALCULATE(
			        SUM(f_capex_imp_cost_data[amount_pln]),
			        d_impl_cat_cost[impl_cat_cost_code] = "A-WDR-99"
			    ),
			    0
			)
		lineageTag: f97acb70-0ba0-46a7-ab96-7f95de9d61d8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		formatString: 0
		lineageTag: 7128fcce-d1b2-4ff6-9247-20bcb975a017
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Miary = calculated
		mode: import
		source = {0}

	annotation PBI_Id = 8ff54b4d66f14635a814d7d3fdcc4732

