table _Miary
	lineageTag: fce809bd-c1a1-4265-b842-278345ddfbe1

	measure Wydatki =
			
			SUM(f_capex_imp_cost_data[amount_pln])
		formatString: #,0.00
		lineageTag: 295b12e5-d9a0-457b-a5b2-7fcb9103c641

	measure 'Nazwa projektu - tytul' =
			
			IF( NOT ISFILTERED(vm_pbi_d_gl_project[prj_desc]),
			    "Wybierz projekt",
			    IF( HASONEVALUE(vm_pbi_d_gl_project[prj_desc]),
			        VALUES(vm_pbi_d_gl_project[prj_desc]),
			        "Kilka projektów" )
			)
		lineageTag: b6e08fcd-fedb-45b4-bb85-c74858294be6

	measure 'Ilość otwartych projektów' =
			
			COUNTROWS (
			    DISTINCT(
			        FILTER(
			            VALUES('vm_pbi_d_gl_project'[prj_desc]),
			            LEFT ('vm_pbi_d_gl_project'[prj_desc], 3) <> "(X)"
			        )
			    )
			)
		formatString: 0
		lineageTag: d8358878-8d59-40fd-a985-73ad8eae745c

	measure 'Ilosc otwartych projektow wg statusow' =
			
			
			COUNTROWS(
			    DISTINCT(
			    FILTER(
			        vm_pbi_d_gl_project,
			        vm_pbi_d_gl_project[status] = "Aktywny"
			    )
			)
			)
		formatString: 0
		lineageTag: ff3f4611-a439-44b2-a121-51817b979cd1

	measure 'Numer projektu - tytul' =
			
			IF( NOT ISFILTERED(vm_pbi_d_gl_project[prj_desc]),
			    "Wybierz projekt",
			    IF( HASONEVALUE(vm_pbi_d_gl_project[hprj_code]),
			        VALUES(vm_pbi_d_gl_project[hprj_code]),
			        "Kilka projektów")
			)
		lineageTag: 0490d09a-711e-4302-9875-25436384c6c6

	measure 'Budzet projektu' = ```
			
			
			SUM(vm_pbi_d_projects_budget[debet_amount])
			
			```
		formatString: #,0.00
		lineageTag: 467e429d-ecbc-48a8-8151-48417635da7e

	measure 'Realizacja budzetu %' = ```
			
			VAR Budzet_projektu = 
			    SUM(vm_pbi_d_projects_budget[debet_amount])
			
			VAR Wydatki = 
			    SUM(f_capex_imp_cost_data[amount_pln])
			
			RETURN
			
			DIVIDE(
			    [Wydatki],
			    [Budzet projektu],
			    ""
			 )
			
			```
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 0a1ed71e-7a2c-4f4e-928f-e3600efa60d1

	measure 'Widocznosc grafiki' = ```
			
			IF(
			    HASONEVALUE(vm_pbi_d_gl_project[prj_desc]),
			    "RGBA(255,0,0,0)",         
			    "RGBA(255,255,255,1)"
			)
			
			```
		lineageTag: 27778e1b-8db4-4dbc-b119-6f3b7b46de78

	measure Sprzedaz =
			
			SUM(vm_pbi_d_gl_project[s_pln_net])
		formatString: #,0.00
		lineageTag: 075e393b-857f-4dff-917e-27c42297f1aa

	measure Marza_II =
			
			SUM(vm_pbi_d_gl_project[m_pln_margin_ii])
		lineageTag: ab0c2d8a-18bb-4ee4-b9c3-65211b64a8d2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Zysk z wdrozenia' =
			
			[Marza_II]-[Wydatki]
		lineageTag: bfb82d26-b167-48a0-9de0-52b3302af165

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Marza_II_% =
			
			DIVIDE(
			    [Marza_II],
			    [Sprzedaz],
			    "brak sprzedaży"
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 76eb7427-cb99-490f-81e7-9c51441295fa

	column Value
		formatString: 0
		lineageTag: 7128fcce-d1b2-4ff6-9247-20bcb975a017
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Miary = calculated
		mode: import
		source = {0}

	annotation PBI_Id = 8ff54b4d66f14635a814d7d3fdcc4732

